- Src/MoneyManager/MoneyManager.Shared/Strings/de/Resources.resw
- Src/MoneyManager/MoneyManager.Shared/Strings/en/Resources.resw
- Src/MoneyManager/MoneyManager.Shared/UserControls/AddTransactionUserControl.xaml
- Src/MoneyManager/MoneyManager.Shared/UserControls/BackupUserControl.xaml
- Src/MoneyManager/MoneyManager.WindowsPhone/Views/SettingsOverview.xaml
some untranslated controls and strings are now translated to english and german
> updated and expanded localization

- Src/MoneyManager/MoneyManager.Shared/Strings/de/Resources.resw
- Src/MoneyManager/MoneyManager.Shared/Strings/en/Resources.resw
- Src/MoneyManager/MoneyManager.WindowsPhone/Common/ReviewHelper.cs
- Src/MoneyManager/MoneyManager.WindowsPhone/MoneyManager.WindowsPhone.csproj
You just need to put a ReviewHelper.AskUserForReview() somewhere in your code. I think it should be on the mainpage.
> Review Helper

- Src/MoneyManager/MoneyManager.Shared/Strings/de/Resources.resw
- Src/MoneyManager/MoneyManager.Shared/Strings/en/Resources.resw
- Src/MoneyManager/MoneyManager.Shared/UserControls/AboutUserControl.xaml
- Src/MoneyManager/MoneyManager.Shared/UserControls/AboutUserControl.xaml.cs
- Src/MoneyManager/MoneyManager.WindowsPhone/Views/About.xaml
> adjustments to the about page.

- Src/MoneyManager.Core.Tests/Bootstrap/SqlitePclPluginBootstrap.cs
- Src/MoneyManager.Core.Tests/MoneyManager.Core.Tests.csproj
- Src/MoneyManager.Core.Tests/packages.config
- Src/MoneyManager.Core/MoneyManager.Core.csproj
- Src/MoneyManager.Core/packages.config
- Src/MoneyManager.DataAccess/MoneyManager.DataAccess.csproj
- Src/MoneyManager.DataAccess/packages.config
- Src/MoneyManager.Droid/Bootstrap/EmailPluginBootstrap.cs
- Src/MoneyManager.Droid/Bootstrap/JsonPluginBootstrap.cs
- Src/MoneyManager.Droid/Bootstrap/VisibilityPluginBootstrap.cs
- Src/MoneyManager.Droid/Bootstrap/WebBrowserPluginBootstrap.cs
- Src/MoneyManager.Droid/MoneyManager.Droid.csproj
- Src/MoneyManager.Droid/packages.config
- Src/MoneyManager.Foundation/MoneyManager.Foundation.csproj
- Src/MoneyManager.Foundation/packages.config
- Src/MoneyManager.Ios/Bootstrap/SqlitePluginBootstrap.cs
- Src/MoneyManager.Ios/MoneyManager.Ios.csproj
- Src/MoneyManager.Ios/packages.config
- Src/MoneyManager.Localization/MoneyManager.Localization.csproj
- Src/MoneyManager.Localization/packages.config
- Src/MoneyManager.TestFoundation/MoneyManager.TestFoundation.csproj
- Src/MoneyManager.TestFoundation/packages.config
- Src/MoneyManager.Windows.Tests/project.json
- Src/MoneyManager.Windows.Tests/project.lock.json
- Src/MoneyManager.Windows/Controls/CustomControls/SwipeableSplitView.cs
- Src/MoneyManager.Windows/Style/AppStyles.xaml
- Src/MoneyManager.Windows/project.json
- Src/MoneyManager.Windows/project.lock.json
> upgrade depencencies 

- Src/MoneyManager.Windows/Controls/AccountListUserControl.xaml
- Src/MoneyManager.Windows/Views/ModifyAccountView.xaml
This should solve issues #525 and #520
> Added scrollviewer in account creation/editing page

- Src/MoneyManager.Core/Authentication/PasswordStorage.cs
- Src/MoneyManager.Windows/Package.appxmanifest
- Src/MoneyManager.Windows/Properties/AssemblyInfo.cs
- Src/MoneyManager.userprefs
this should hopefully fix this bug #526.
> replace com exception with system.exception

- Src/MoneyManager.Core/App.cs
- Src/MoneyManager.Core/Helpers/StreamExtension.cs
- Src/MoneyManager.Core/MoneyManager.Core.csproj
- Src/MoneyManager.Core/OneDriveService.cs
- Src/MoneyManager.Core/packages.config
- Src/MoneyManager.Droid/Bootstrap/FilePluginBootstrap.cs
- Src/MoneyManager.Droid/MoneyManager.Droid.csproj
- Src/MoneyManager.Droid/packages.config
- Src/MoneyManager.Foundation/Interfaces/IBackupService.cs
- Src/MoneyManager.Foundation/Interfaces/IOneDriveAuthenticator.cs
- Src/MoneyManager.Foundation/MoneyManager.Foundation.csproj
- Src/MoneyManager.Foundation/packages.config
- Src/MoneyManager.Ios/Bootstrap/FilePluginBootstrap.cs
- Src/MoneyManager.Ios/MoneyManager.Ios.csproj
- Src/MoneyManager.Ios/packages.config
- Src/MoneyManager.Tasks.Windows/project.lock.json
- Src/MoneyManager.Windows.Concrete/MoneyManager.Windows.Concrete.csproj
- Src/MoneyManager.Windows.Concrete/Services/OneDriveAuthenticator.cs
- Src/MoneyManager.Windows.Concrete/project.json
- Src/MoneyManager.Windows.Concrete/project.lock.json
- Src/MoneyManager.Windows.Tests/project.lock.json
- Src/MoneyManager.Windows/Setup.cs
- Src/MoneyManager.Windows/project.json
- Src/MoneyManager.Windows/project.lock.json
> Refactor onedrive

- Src/MoneyManager.Core/ViewModels/Dialogs/CategoryDialogViewModel.cs
- Src/MoneyManager.Localization/Strings.Designer.cs
- Src/MoneyManager.Localization/Strings.de.resx
- Src/MoneyManager.Localization/Strings.resx
- Src/MoneyManager.Windows/Dialogs/ModifyCategoryDialog.cs
- Src/MoneyManager.Windows/Dialogs/ModifyCategoryDialog.xaml
- Src/MoneyManager.Windows/Strings/de/Resources.resw
- Src/MoneyManager.Windows/Strings/en/Resources.resw
- Src/MoneyManager.Windows/Views/SelectCategoryListView.xaml
> add missing translations

- Src/MoneyManager.Core/CoreModule.cs
- Src/MoneyManager.Core/MoneyManager.Core.csproj
- Src/MoneyManager.Core/ViewModels/BaseViewModel.cs
- Src/MoneyManager.Core/ViewModels/CategoryList/SelectCategoryListViewModel.cs
- Src/MoneyManager.Core/ViewModels/ModifyTransactionViewModel.cs
- Src/MoneyManager.Core/packages.config
- Src/MoneyManager.Droid/Activities/SelectCategoryListActivity.cs
- Src/MoneyManager.Droid/Bootstrap/MessengerPluginBootstrap.cs
- Src/MoneyManager.Droid/Fragments/ModifyCategoryDialog.cs
- Src/MoneyManager.Droid/MoneyManager.Droid.csproj
- Src/MoneyManager.Droid/packages.config
- Src/MoneyManager.Foundation/Messages/CategorySelectedMessage.cs
- Src/MoneyManager.Foundation/MoneyManager.Foundation.csproj
- Src/MoneyManager.Ios/Bootstrap/MessengerPluginBootstrap.cs
- Src/MoneyManager.Ios/MoneyManager.Ios.csproj
- Src/MoneyManager.Ios/Setup.cs
- Src/MoneyManager.Ios/packages.config
- Src/MoneyManager.Windows/Dialogs/ModifyCategoryDialog.cs
- Src/MoneyManager.Windows/Dialogs/ModifyCategoryDialog.xaml
- Src/MoneyManager.Windows/Dialogs/SelectDateRangeDialog.xaml
- Src/MoneyManager.Windows/Dialogs/SelectDateRangeDialog.xaml.cs
- Src/MoneyManager.Windows/Setup.cs
- Src/MoneyManager.Windows/project.json
- Src/MoneyManager.Windows/project.lock.json
Use messenger instead of other strange ways via data repository etc. this will be an ongoing task.
> Refactor dataexchange

- Src/MoneyManager.Windows/Views/LoginView.xaml.cs
> fix resolving of Password Storage

- Src/MoneyManager.Windows/Views/ModifyTransactionView.xaml
the icon for clearing the category selection wasn't visible due to the
wrong theme color staticly set.
#601
> Delete category selection

- Src/MoneyManager.Core/ViewModels/ModifyTransactionViewModel.cs
> Fix accounts in modify transaction view

- Src/MoneyManager.Windows/AppShell.xaml
- Src/MoneyManager.Windows/Controls/BalanceUserControl.xaml
- Src/MoneyManager.Windows/Controls/BalanceUserControl.xaml.cs
- Src/MoneyManager.Windows/Dialogs/SelectDateRangeDialog.xaml
- Src/MoneyManager.Windows/Strings/de/Resources.resw
- Src/MoneyManager.Windows/Strings/en/Resources.resw
> Translation

- Src/MoneyManager.Windows/AppShell.xaml
- Src/MoneyManager.Windows/Controls/BalanceUserControl.xaml
- Src/MoneyManager.Windows/Controls/BalanceUserControl.xaml.cs
> Displaymode

- Src/MoneyManager.Core/Manager/RepositoryManager.cs
- Src/MoneyManager.Core/Repositories/TransactionRepository.cs
- Src/MoneyManager.Core/ViewModels/TransactionListViewModel.cs
- Src/MoneyManager.DataAccess/TransactionDataAccess.cs
> Refactor dataloading

- Src/MoneyManager.Windows/AppShell.xaml.cs
> Accounts navmenubutton is now selected at app launch

- Src/MoneyManager.Windows/AppShell.xaml.cs
- Src/MoneyManager.Windows/Controls/CustomControls/SwipeableSplitView.cs
> fix startupcrash and close splitview on click

- Src/MoneyManager.Windows/AppShell.xaml
- Src/MoneyManager.Windows/AppShell.xaml.cs
> support for mouse buttons

- Src/MoneyManager.Windows/Views/StatisticsView.xaml
Maybe now it'll stay that way. #634
> Moved statistics commandbar to a new grid row

- Src/MoneyManager.Core/DateListGroup.cs
> changes the sort

- Src/MoneyManager.Windows/Controls/AccountListUserControl.xaml
> add scrollviewer to account list

- Src/MoneyManager.Windows/Views/ModifyPaymentView.xaml
> overlapping splitview

- Src/MoneyManager.Core.Tests/StatisticProvider/CategorySpreadingProviderTests.cs
- Src/MoneyManager.Core/Repositories/AccountRepository.cs
- Src/MoneyManager.Core/Repositories/CategoryRepository.cs
- Src/MoneyManager.Core/Repositories/PaymentRepository.cs
- Src/MoneyManager.Core/ViewModels/AbstractCategoryListViewModel.cs
- Src/MoneyManager.Windows.DataAccess.Tests/RecurringPaymentDataAccessTests.cs
> update gui properly

- Src/MoneyManager.Core/Repositories/AccountRepository.cs
- Src/MoneyManager.Core/Repositories/CategoryRepository.cs
- Src/MoneyManager.Core/Repositories/PaymentRepository.cs
- Src/MoneyManager.Core/ViewModels/ModifyPaymentViewModel.cs
- Src/MoneyManager.Foundation/Interfaces/IAccountRepository.cs
> fix bug when move transaction between accounts

- Src/MoneyManager.DataAccess/PaymentDataAccess.cs
> fix bug with saving a recurring transaction

- Src/MoneyManager.Core/ViewModels/PaymentListViewModel.cs
- Src/MoneyManager.Windows/Views/UserControls/PaymentListUserControl.xaml
- Src/MoneyManager.Windows/Views/UserControls/PaymentListUserControl.xaml.cs
> fix bug with edit over context menu, remove unused code

- Src/MoneyManager.Core/Services/OneDriveService.cs
- Src/MoneyManager.Core/ViewModels/ModifyPaymentViewModel.cs
- Src/MoneyManager.Core/ViewModels/PaymentListViewModel.cs
- Src/MoneyManager.Windows/MoneyManager.Windows.csproj
> some bugfixes

- Src/MoneyFox.Shared/Interfaces/INotificationService.cs
- Src/MoneyFox.Shared/MoneyFox.Shared.csproj
- Src/MoneyFox.Shared/ViewModels/ModifyAccountViewModel.cs
- Src/MoneyFox.Windows/MoneyFox.Windows.csproj
- Src/MoneyFox.Windows/Services/NotificationService.cs
- Src/MoneyFox.Windows/Setup.cs
As discussed in PR #851, I replaced the "account created" dialog with a toast notification, fixing issues #853 and #831. I also added a new interface and a service to send toast notifications (I only added a basic one, but could be extended with  interactive notifications).
> Replaced dialog with toast notification

- Src/MoneyFox.Shared/Helpers/Settings.cs
- Src/MoneyFox.Shared/SqliteConnectionCreator.cs
- Src/MoneyFox.Shared/ViewModels/PersonalizationUserControlViewModel.cs
- Src/MoneyFox.Shared/ViewModels/StatisticCashFlowViewModel.cs
- Src/MoneyFox.Shared/ViewModels/StatisticCategorySpreadingViewModel.cs
- Src/MoneyFox.Shared/ViewModels/StatisticMonthlyExpensesViewModel.cs
- Src/MoneyFox.Windows/App.xaml
- Src/MoneyFox.Windows/Converter/AccountListVisibilityConverter.cs
- Src/MoneyFox.Windows/Views/PaymentListView.xaml
- Src/MoneyFox.Windows/Views/StatisticCashFlowView.xaml
- Src/MoneyFox.Windows/Views/UserControls/PaymentListUserControl.xaml
- Src/MoneyFox.Windows/Views/UserControls/PaymentListUserControl.xaml.cs
> fix different smaller issues

- Src/MoneyFox.Shared/Resources/Strings.Designer.cs
- Src/MoneyFox.Shared/Resources/Strings.resx
- Src/MoneyFox.Windows/Converter/BackupDateVisibilityConverter.cs
- Src/MoneyFox.Windows/Converter/PaymentHeaderConverter.cs
- Src/MoneyFox.Windows/MoneyFox.Windows.csproj
- Src/MoneyFox.Windows/Views/BackupView.xaml
- Src/MoneyFox.Windows/Views/ModifyPaymentView.xaml
> The page header when adding payment changes according to the payment's type

- Src/MoneyFox.Shared/DataAccess/AbstractDataAccess.cs
- Src/MoneyFox.Shared/Interfaces/IDataAccess.cs
- Src/MoneyFox.Shared/Repositories/AccountRepository.cs
- Src/MoneyFox.Shared/Repositories/CategoryRepository.cs
- Src/MoneyFox.Shared/Repositories/PaymentRepository.cs
- Src/MoneyFox.Shared/Resources/Strings.Designer.cs
- Src/MoneyFox.Shared/Resources/Strings.resx
- Src/MoneyFox.Shared/ViewModels/ModifyAccountViewModel.cs
> refactor notification

- Src/MoneyFox.Droid/Bootstrap/ConnectivityPluginBootstrap.cs
- Src/MoneyFox.Droid/MoneyFox.Droid.csproj
- Src/MoneyFox.Droid/Properties/AndroidManifest.xml
- Src/MoneyFox.Droid/packages.config
- Src/MoneyFox.Shared/MoneyFox.Shared.csproj
- Src/MoneyFox.Shared/Resources/Strings.Designer.cs
- Src/MoneyFox.Shared/Resources/Strings.resx
- Src/MoneyFox.Shared/ViewModels/BackupViewModel.cs
- Src/MoneyFox.Shared/packages.config
- Src/MoneyFox.Tasks/project.lock.json
- Src/MoneyFox.Windows.Tests/project.lock.json
- Src/MoneyFox.Windows/Package.appxmanifest
- Src/MoneyFox.Windows/Setup.cs
- Src/MoneyFox.Windows/Style/AppStyles.xaml
- Src/MoneyFox.Windows/Style/ControlStyles.xaml
- Src/MoneyFox.Windows/Views/AppShell.xaml
- Src/MoneyFox.Windows/Views/AppShell.xaml.cs
- Src/MoneyFox.Windows/project.json
- Src/MoneyFox.Windows/project.lock.json
> fix color of toggle button, improve menu functionality

- Src/MoneyFox.Shared.Tests/Repositories/AccountRepositoryTests.cs
- Src/MoneyFox.Shared.Tests/Repositories/CategoryRepositoryTests.cs
- Src/MoneyFox.Shared.Tests/Repositories/PaymentRepositoryTests.cs
- Src/MoneyFox.Shared/App.cs
- Src/MoneyFox.Shared/AppStart.cs
- Src/MoneyFox.Shared/DataAccess/AccountDataAccess.cs
- Src/MoneyFox.Shared/Helpers/SettingsHelper.cs
- Src/MoneyFox.Shared/Manager/AutoBackupManager.cs
- Src/MoneyFox.Shared/MoneyFox.Shared.csproj
- Src/MoneyFox.Shared/Repositories/AccountRepository.cs
- Src/MoneyFox.Shared/Repositories/PaymentRepository.cs
- Src/MoneyFox.Shared/ViewModels/StatisticMonthlyExpensesViewModel.cs
- Src/MoneyFox.Windows/App.xaml.cs
- Src/MoneyFox.Windows/Package.appxmanifest
- Src/MoneyFox.Windows/Strings/en/Resources.resw
- Src/MoneyFox.Windows/Views/LoginView.xaml.cs
- Src/MoneyFox.Windows/Views/SettingsView.xaml
- Src/MoneyFox.Windows/Views/UserControls/SettingsGeneralUserControl.xaml
- Src/MoneyFox.Windows/Views/UserControls/SettingsPersonalizationUserControl.xaml
> implement auto backup

- Src/MoneyFox.Droid/Fragments/SettingsFragment.cs
- Src/MoneyFox.Droid/Fragments/SettingsGeneral.cs
- Src/MoneyFox.Droid/MoneyFox.Droid.csproj
- Src/MoneyFox.Droid/Resources/Resource.Designer.cs
- Src/MoneyFox.Droid/Resources/layout/fragment_settings_general.axml
- Src/MoneyFox.Droid/Resources/values/Strings.xml
- Src/MoneyFox.Shared/Helpers/SettingsHelper.cs
- Src/MoneyFox.Shared/Resources/Strings.Designer.cs
- Src/MoneyFox.Shared/Resources/Strings.resx
> autobackup setting in android

- Src/MoneyFox.Shared.Tests/ViewModels/ModifyAccountViewModelTests.cs
- Src/MoneyFox.Shared/Resources/Strings.Designer.cs
- Src/MoneyFox.Shared/Resources/Strings.resx
- Src/MoneyFox.Shared/ViewModels/ModifyAccountViewModel.cs
#946 Added a form of validation for accounts and some tests around saving as well.
> Added some validation for Accounts with duplicate names

- Src/MoneyFox.Tasks/ClearPaymentBackgroundTask.cs
- Src/MoneyFox.Windows/Src/Shortcuts/Tile.cs
> Fix live tile on windows.

- Src/MoneyFox.Droid/MoneyFox.Droid.csproj
- Src/MoneyFox.Droid/Resources/layout/fragment_backup.axml
- Src/MoneyFox.Droid/Services/DialogService.cs
- Src/MoneyFox.Droid/app.config
- Src/MoneyFox.Droid/packages.config
- Src/MoneyFox.Shared/Interfaces/IDialogService.cs
- Src/MoneyFox.Shared/Resources/Strings.Designer.cs
- Src/MoneyFox.Shared/Resources/Strings.resx
- Src/MoneyFox.Shared/ViewModels/BackupViewModel.cs
- Src/MoneyFox.Windows/MoneyFox.Windows.csproj
- Src/MoneyFox.Windows/Services/DialogService.cs
- Src/MoneyFox.Windows/Strings/en/Resources.resw
- Src/MoneyFox.Windows/Views/BackupView.xaml
- Src/MoneyFox.Windows/Views/Dialogs/LoadingDialog.xaml
- Src/MoneyFox.Windows/Views/Dialogs/LoadingDialog.xaml.cs
Add a Loading Dialog to the IDialogService and implement it on Windows and Android.
> Loading dialog

- Src/MoneyFox.Droid/Properties/AndroidManifest.xml
- Src/MoneyFox.Windows/Views/ModifyPaymentView.xaml.cs
> Category not selected

- Src/MoneyFox.Shared.Tests/ViewModels/ModifyPaymentViewModelTest.cs
- Src/MoneyFox.Shared/ViewModels/ModifyPaymentViewModel.cs
- Src/MoneyFox.Windows/MoneyFox.Windows.csproj
- Src/MoneyFox.Windows/Views/ModifyPaymentView.xaml
ok, 
here is my revised commit for issue 952.  I am not familiar enough with c# to write a more concise command so please feel free to revise it.  I also have never written a unit test before but I think that what I wrote works.  
Thanks!
> Revised Pull Request Issue #952

- Src/MoneyFox.Shared/ViewModels/AccountListViewModel.cs
> Update IsAllAccountsEmpty to handle Null values

- Src/MoneyFox.Business/Manager/BackupManager.cs
- Src/MoneyFox.Business/Services/OneDriveService.cs
- Src/MoneyFox.Business/ViewModels/BackupViewModel.cs
- Src/MoneyFox.Droid/OneDriveAuth/DroidAuthenticationProvider.cs
- Src/MoneyFox.Droid/OneDriveAuth/OneDriveAuthenticator.cs
- Src/MoneyFox.Droid/Resources/layout/fragment_backup.axml
- Src/MoneyFox.Foundation/Constants/ServiceConstants.cs
- Src/MoneyFox.Foundation/Interfaces/IBackupManager.cs
- Src/MoneyFox.Foundation/Interfaces/IBackupService.cs
- Src/MoneyFox.Foundation/Interfaces/IOneDriveAuthenticator.cs
- Src/MoneyFox.Shared.Tests/ViewModels/BackupViewModelTests.cs
- Src/MoneyFox.Windows.Business/OneDriveAuthenticator.cs
- Src/MoneyFox.Windows/Views/BackupView.xaml
> Readd logout button

- Src/MoneyFox.Business/BusinessModule.cs
- Src/MoneyFox.Business/Helpers/GlobalBusyIndicatorState.cs
- Src/MoneyFox.Business/Manager/AutoBackupManager.cs
- Src/MoneyFox.Business/MoneyFox.Business.csproj
- Src/MoneyFox.Business/ViewModels/AbstractCategoryListViewModel.cs
- Src/MoneyFox.Business/ViewModels/AccountListViewModel.cs
- Src/MoneyFox.Business/ViewModels/ModifyPaymentViewModel.cs
- Src/MoneyFox.Business/ViewModels/SettingsViewModel.cs
- Src/MoneyFox.Droid/Activities/PaymentListActivity.cs
- Src/MoneyFox.Droid/Activities/SelectCategoryListActivity.cs
- Src/MoneyFox.Droid/DroidModule.cs
- Src/MoneyFox.Droid/Fragments/CategoriesFragment.cs
- Src/MoneyFox.Droid/Manager/TileManager.cs
- Src/MoneyFox.Droid/MoneyFox.Droid.csproj
- Src/MoneyFox.Droid/Services/SyncBackupService.cs
- Src/MoneyFox.Shared.Tests/ViewModels/CategoryListViewModelTests.cs
- Src/MoneyFox.Windows.Tasks/SyncBackupTask.cs
- Src/MoneyFox.Windows/Views/CategoryListView.xaml
- Src/MoneyFox.Windows/Views/SelectCategoryListView.xaml
- Src/MoneyFox.Windows/Views/UserControls/PageHeader.xaml
- Src/MoneyFox.Windows/Views/UserControls/PageHeader.xaml.cs
- Src/MoneyFox.Windows/WindowsModule.cs
> different bug fixes

- Src/MoneyFox.Business/ViewModels/ModifyCategoryViewModel.cs
- Src/MoneyFox.Droid/Properties/AndroidManifest.xml
- Src/MoneyFox.Windows/Src/TileHelper.cs
- Src/MoneyFox.Windows/Views/ModifyCategoryView.xaml.cs
- Src/MoneyFox.Windows/Views/ModifyPaymentView.xaml.cs
> Fix tile navigation

- Src/MoneyFox.Foundation/Resources/Strings.Designer.cs
- Src/MoneyFox.Foundation/Resources/Strings.nl.resx
- Src/MoneyFox.Foundation/Resources/Strings.resx
Update string files to contain "Search" instead of "Search String".
> Changed any "Search String" to "Search".

- Src/MoneyFox.Windows/MoneyFox.Windows.csproj
- Src/MoneyFox.Windows/Services/MicrosoftPassportHelper.cs
- Src/MoneyFox.Windows/Views/LoginView.xaml
- Src/MoneyFox.Windows/Views/LoginView.xaml.cs
> Microsoft Passport added to Login

- Src/MoneyFox.Business/Authentication/Session.cs
- Src/MoneyFox.Business/Manager/SettingsManager.cs
- Src/MoneyFox.Business/ViewModels/LoginViewModel.cs
- Src/MoneyFox.Business/ViewModels/SettingsSecurityViewModel.cs
- Src/MoneyFox.Droid/MoneyFox.Droid.csproj.bak
- Src/MoneyFox.Foundation/Interfaces/ISettingsManager.cs
- Src/MoneyFox.Windows/Services/MicrosoftPassportHelper.cs
- Src/MoneyFox.Windows/Views/LoginView.xaml
- Src/MoneyFox.Windows/Views/LoginView.xaml.cs
- Src/MoneyFox.Windows/Views/UserControls/SettingsSecurityUserControl.xaml
- Src/MoneyFox.Windows/Views/UserControls/SettingsSecurityUserControl.xaml.cs
Added selection toggle for passport in security view.
> Added select toggle for passport

- Src/MoneyFox.Business/Helpers/RecurringPaymentHelper.cs
- Src/MoneyFox.Business/Manager/PaymentManager.cs
- Src/MoneyFox.Droid/MoneyFox.Droid.csproj
- Src/MoneyFox.Droid/MoneyFox.Droid.csproj.bak
- Src/MoneyFox.Droid/MoneyFox.Droid.nuget.props
Update recurring payment to last day of month for different month lengths.  Issue #1180.
> update recurring payment

- Src/MoneyFox.Droid/Fragments/CategoriesFragment.cs
- Src/MoneyFox.Droid/Resources/layout/fragment_category_list.axml
> try to fix issues with categories list

- Src/MoneyFox.Business.Tests/ViewModels/ModifyCategoryViewModelTests.cs
- Src/MoneyFox.Business/AppStart.cs
- Src/MoneyFox.Business/Manager/BackupManager.cs
- Src/MoneyFox.Business/ViewModels/AccountViewModel.cs
- Src/MoneyFox.Business/ViewModels/BackupViewModel.cs
- Src/MoneyFox.Business/ViewModels/CategoryViewModel.cs
- Src/MoneyFox.DataAccess/ApplicationContext.cs
- Src/MoneyFox.DataAccess/ApplicationContextOld.cs
- Src/MoneyFox.DataAccess/Entities/CategoryEntity.cs
- Src/MoneyFox.DataAccess/EntityOld/Account.cs
- Src/MoneyFox.DataAccess/EntityOld/Category.cs
- Src/MoneyFox.DataAccess/EntityOld/Payment.cs
- Src/MoneyFox.DataAccess/EntityOld/RecurringPayment.cs
- Src/MoneyFox.DataAccess/Infrastructure/DbFactory.cs
- Src/MoneyFox.DataAccess/Infrastructure/Disposable.cs
- Src/MoneyFox.DataAccess/Infrastructure/RepositoryBase.cs
- Src/MoneyFox.DataAccess/Migrations/20170506145232_InitMigration.cs
- Src/MoneyFox.DataAccess/MoneyFox.DataAccess.csproj
- Src/MoneyFox.DataAccess/UnitOfWork.cs
- Src/MoneyFox.Droid/Activities/MainActivity.cs
- Src/MoneyFox.Droid/Activities/SplashScreenActivity.cs
- Src/MoneyFox.Droid/project.json
- Src/MoneyFox.Foundation/Constants/DatabaseConstants.cs
- Src/MoneyFox.Foundation/Groups/DateListGroup.cs
- Src/MoneyFox.Service/OneDriveService.cs
- Src/MoneyFox.Service/RecurringPaymentHelper.cs
- Src/MoneyFox.Windows/App.xaml.cs
Migrate the database from the old data to the new database.
> Migrate data

- Src/MoneyFox.Business/AppStart.cs
- Src/MoneyFox.Business/Manager/BackupManager.cs
- Src/MoneyFox.DataAccess/ApplicationContext.cs
- Src/MoneyFox.DataAccess/Infrastructure/DbFactory.cs
- Src/MoneyFox.DataAccess/Infrastructure/RepositoryBase.cs
fix  #1292 
fix #1291
fix #1288
> Use current data after restore backup

- Src/MoneyFox.Foundation/Resources/Strings.Designer.cs
- Src/MoneyFox.Foundation/Resources/Strings.bg.resx
- Src/MoneyFox.Foundation/Resources/Strings.es.resx
- Src/MoneyFox.Foundation/Resources/Strings.fr.resx
- Src/MoneyFox.Foundation/Resources/Strings.it.resx
- Src/MoneyFox.Foundation/Resources/Strings.nl.resx
- Src/MoneyFox.Foundation/Resources/Strings.resx
- Src/MoneyFox.Foundation/Resources/Strings.zh-CN.resx
- Src/MoneyFox.Windows/Strings/en/Resources.resw
- Src/MoneyFox.Windows/Strings/it/Resources.resw
- Src/MoneyFox.Windows/Views/CategoryListView.xaml
- Src/MoneyFox.Windows/Views/UserControls/SettingsPersonalizationUserControl.xaml
Corrected the grammar in some places and fixed the new category label so that
it would say "New Category" instead of "New CategoryViewModel". I also
replaced \n with a shift enter in the resx files since \n was showing on
the screen instead of an actual new line.
> Corrected some grammar and fixed new category label

- Src/MoneyFox.Business/MoneyFox.Business.csproj
- Src/MoneyFox.Business/ViewModels/PaymentListBalanceViewModel.cs
- Src/MoneyFox.Windows/Package.appxmanifest
- Src/MoneyFox.Windows/Views/ModifyPaymentView.xaml.cs
tries to fix two of the most occuring crashes on windows.
> Fix crashes

- Src/MoneyFox.DataAccess/DataServices/PaymentService.cs
> Include categories for clearing payments.

- Src/MoneyFox.Business/Messages/FilterChangedMessage.cs
- Src/MoneyFox.Business/ViewModels/Interfaces/IPaymentListViewActionViewModel.cs
- Src/MoneyFox.Business/ViewModels/ModifyPaymentViewModel.cs
- Src/MoneyFox.Business/ViewModels/PaymentListViewActionViewModel.cs
- Src/MoneyFox.Business/ViewModels/PaymentListViewModel.cs
- Src/MoneyFox.Business/ViewModels/SelectFilterDialogViewModel.cs
- Src/MoneyFox.Droid/Activities/PaymentListActivity.cs
- Src/MoneyFox.Droid/Dialogs/SelectFilterDialog.cs
- Src/MoneyFox.Droid/MoneyFox.Droid.csproj
- Src/MoneyFox.Droid/Resources/layout/dialog_select_filter.axml
- Src/MoneyFox.Foundation/Resources/Strings.Designer.cs
- Src/MoneyFox.Foundation/Resources/Strings.resx
- Src/MoneyFox.Windows/MoneyFox.Windows.csproj
- Src/MoneyFox.Windows/Package.StoreAssociation.xml
- Src/MoneyFox.Windows/Package.appxmanifest
- Src/MoneyFox.Windows/Strings/en/Resources.resw
- Src/MoneyFox.Windows/Views/ModifyPaymentView.xaml
- Src/MoneyFox.Windows/Views/PaymentListView.xaml
- Src/MoneyFox.Windows/Views/UserControls/PaymentListUserControl.xaml
> Time filter

- Src/MoneyFox.Android/MoneyFox.Android.csproj
- Src/MoneyFox.Business.Tests/MoneyFox.Business.Tests.csproj
- Src/MoneyFox.Business/MoneyFox.Business.csproj
- Src/MoneyFox.DataAccess/MoneyFox.DataAccess.csproj
- Src/MoneyFox.Foundation/MoneyFox.Foundation.csproj
- Src/MoneyFox.Ios/MoneyFox.iOS.csproj
- Src/MoneyFox.Windows.Tasks/MoneyFox.Windows.Tasks.csproj
- Src/MoneyFox.Windows/MoneyFox.Windows.csproj
- Src/MoneyFox/MoneyFox.csproj
move back to mvvmcross 6.1.1 to fix #1386
> fix issue with back button on android

- Src/MoneyFox.Business/ViewModels/SelectCategoryListViewModel.cs
- Src/MoneyFox/Converter/EmptyNameConverter.cs
- Src/MoneyFox/Views/ModifyPaymentPage.xaml
- Src/MoneyFox/Views/ModifyPaymentPage.xaml.cs
- Src/MoneyFox/Views/SelectCategoryPage.xaml
- Src/MoneyFox/Views/SelectCategoryPage.xaml.cs
> replace entry with button to select category in xamarin

- Src/MoneyFox.Windows/App.xaml.cs
- Src/MoneyFox.Windows/Style/AppStyles.xaml
- Src/MoneyFox.Windows/Style/ColorsDark.xaml
- Src/MoneyFox.Windows/Style/ColorsLight.xaml
- Src/MoneyFox.Windows/Style/TextStyles.xaml
- Src/MoneyFox.Windows/Views/AboutView.xaml
- Src/MoneyFox.Windows/Views/AccountListView.xaml
- Src/MoneyFox.Windows/Views/CategoryListView.xaml
- Src/MoneyFox.Windows/Views/MainView.xaml
- Src/MoneyFox.Windows/Views/ModifyAccountView.xaml
- Src/MoneyFox.Windows/Views/ModifyCategoryView.xaml
- Src/MoneyFox.Windows/Views/ModifyPaymentView.xaml
- Src/MoneyFox.Windows/Views/PaymentListView.xaml
- Src/MoneyFox.Windows/Views/SelectCategoryListView.xaml
- Src/MoneyFox.Windows/Views/SettingsView.xaml
- Src/MoneyFox.Windows/Views/StatisticCashFlowView.xaml
- Src/MoneyFox.Windows/Views/StatisticCategorySpreadingView.xaml
- Src/MoneyFox.Windows/Views/StatisticCategorySummaryView.xaml
- Src/MoneyFox.Windows/Views/StatisticSelectorView.xaml
this is a fix for #1364 and some other small design topics.
For now the minimal mode is disabled since I wasn't able to figure out how to adjust the colors for the menu buttons and title with an adaptive trigger.
As soon as support for a mobile plattform is wished again, this should be revised again.
Also as far as I could figure out the back button and the minimize, maximize and close buttons have to have the same style. Therefore I had to pick one that is kinda visible on both areas.
> Some design adjustments for windows

- Src/MoneyFox.Android/MoneyFox.Android.csproj
- Src/MoneyFox.Business.Tests/MoneyFox.Business.Tests.csproj
- Src/MoneyFox.Business/MoneyFox.Business.csproj
- Src/MoneyFox.DataAccess.Tests/MoneyFox.DataAccess.Tests.csproj
- Src/MoneyFox.DataAccess/MoneyFox.DataAccess.csproj
- Src/MoneyFox.Foundation/MoneyFox.Foundation.csproj
- Src/MoneyFox.Ios/Info.plist
- Src/MoneyFox.Ios/MoneyFox.iOS.csproj
- Src/MoneyFox.Windows.Tasks/MoneyFox.Windows.Tasks.csproj
- Src/MoneyFox.Windows/MoneyFox.Windows.csproj
- Src/MoneyFox/MoneyFox.csproj
Reverts MoneyFox/MoneyFox#1473
> Revert "Update nuget packages"

- Src/MoneyFox.Android/Jobs/SyncBackupJob.cs
- Src/MoneyFox.Android/MoneyFox.Android.csproj
- Src/MoneyFox.Android/Setup.cs
- Src/MoneyFox.Business.Tests/MoneyFox.Business.Tests.csproj
- Src/MoneyFox.Business.Tests/ViewModels/BackupViewModelTests.cs
- Src/MoneyFox.Business/Adapter/ConnectivtyAdapter.cs
- Src/MoneyFox.Business/Manager/BackupManager.cs
- Src/MoneyFox.Business/MoneyFox.Business.csproj
- Src/MoneyFox.Business/ViewModels/BackupViewModel.cs
- Src/MoneyFox.Ios/AppDelegate.cs
- Src/MoneyFox.Ios/MoneyFox.iOS.csproj
- Src/MoneyFox.Ios/Setup.cs
- Src/MoneyFox.Windows.Tasks/MoneyFox.Windows.Tasks.csproj
- Src/MoneyFox.Windows.Tasks/SyncBackupTask.cs
- Src/MoneyFox.Windows/MoneyFox.Windows.csproj
- Src/MoneyFox.Windows/Setup.cs
Issue: #
This does replace the connectivity plugin in favor of Xamarin.Essentials. Hopefully this fixes and array of crashes when Network Changed iis called.
- Bugfix
Checks the Network connection. In some cases this lead to crashes according to the appcenter and the windows dev center.
Checks the network connection and catches occuring excpetions.
> Replace connectivity plugin

- Src/MoneyFox.BusinessLogic/PaymentActions/ModifyPaymentAction.cs
- Src/MoneyFox.DataLayer.Tests/Entities/AccountTests.cs
- Src/MoneyFox.DataLayer/Entities/Account.cs
- Src/MoneyFox.Presentation/Views/PaymentListPage.xaml
- Src/MoneyFox.ServiceLayer.Tests/Authentication/SessionTests.cs
- Src/MoneyFox.ServiceLayer.Tests/ViewModels/PaymentListViewModelTests.cs
- Src/MoneyFox.ServiceLayer/Services/PaymentService.cs
- Src/MoneyFox.ServiceLayer/ViewModels/DesignTime/DesignTimePaymentListViewModel.cs
- Src/MoneyFox.ServiceLayer/ViewModels/Interfaces/IPaymentListViewModel.cs
- Src/MoneyFox.ServiceLayer/ViewModels/PaymentListViewModel.cs
- Src/MoneyFox.Uwp/Package.StoreAssociation.xml
- Src/MoneyFox.Uwp/Package.appxmanifest
- Src/MoneyFox.Uwp/Views/UserControls/PaymentListUserControl.xaml
Issue: #
fix #1491 
fix #1490 
- Bugfix
> Fix payment list

- Src/MoneyFox.BusinessLogic/Extensions/DateTimeExtension.cs
- Src/MoneyFox.BusinessLogic/PaymentActions/RecurringPaymentAction.cs
- Src/MoneyFox.BusinessLogic/PaymentActions/RecurringPaymentHelper.cs
- Src/MoneyFox.DataLayer/Entities/Payment.cs
- Src/MoneyFox.ServiceLayer/ViewModels/PaymentListViewActionViewModel.cs
- Src/MoneyFox.Uwp.Tasks/LiveTiles.cs
Issue: #
#1494 
- Bugfix 
The recurring payments are not created correctly.  With that they where repeateadly created multiple times.
The payments should now be created correctly.
- [] Tested code on iOS
> Fix recurring payment

- Src/MoneyFox.DataLayer.Tests/Entities/RecurringPaymentTests.cs
- Src/MoneyFox.DataLayer/Entities/RecurringPayment.cs
- Src/MoneyFox.Migrations.Startup/MoneyFox.Migrations.Startup.csproj
- Src/MoneyFox.ServiceLayer.Tests/ViewModels/EditPaymentViewModelTests.cs
- Src/MoneyFox.ServiceLayer/Services/PaymentService.cs
- Src/MoneyFox.ServiceLayer/ViewModels/EditPaymentViewModel.cs
- Src/MoneyFox.ServiceLayer/ViewModels/RecurringPaymentViewModel.cs
- Src/MoneyFox.Uwp/App.xaml.cs
- Src/MoneyFox.sln
Issue: #
#1503 
- Bugfix
It crashes when a recurring payment is opened.
Recurring payments with no enddate get one set. Also they get saved correctly when they are not endless.
> Fix edit recurring

- Src/MoneyFox.Presentation/Views/StatisticCategorySummaryPage.xaml
Issue: #
#1501 
- Bugfix 
Alignment for category summary is not correct.
Correct alligned.
> Fix category summary alignment

- Src/MoneyFox.Uwp/Src/BackgroundTaskManager.cs
Issue: #
#1516
- Bugfix 
Background sync is not done automatically on windows.
It should be done automatically when sync is deactivated and activated again.
> uncomment the background task

- Src/MoneyFox.BusinessLogic/PaymentActions/ModifyPaymentAction.cs
- Src/MoneyFox.DataLayer.Tests/Entities/PaymentTests.cs
- Src/MoneyFox.DataLayer/Entities/Payment.cs
- Src/MoneyFox.ServiceLayer.Tests/ViewModels/AddPaymentViewModelTests.cs
- Src/MoneyFox.ServiceLayer.Tests/ViewModels/EditPaymentViewModelTests.cs
- Src/MoneyFox.ServiceLayer/Services/PaymentService.cs
- Src/MoneyFox.ServiceLayer/ViewModels/AddPaymentViewModel.cs
- Src/MoneyFox.ServiceLayer/ViewModels/EditPaymentViewModel.cs
Issue: #
#1521 
- Bugfix 
If you have edit a payment and adjust the amount it does not remove the former amount and add the new but just add the amount again.
payment amounts are now calculated correctly.
> Fix modify payment

- Src/MoneyFox.Android/MoneyFox.Android.csproj
- Src/MoneyFox.BusinessLogic.Tests/MoneyFox.BusinessLogic.Tests.csproj
- Src/MoneyFox.BusinessLogic/MoneyFox.BusinessLogic.csproj
- Src/MoneyFox.DataLayer/EfCoreContext.cs
- Src/MoneyFox.DataLayer/Entities/Payment.cs
- Src/MoneyFox.DataLayer/MoneyFox.DataLayer.csproj
- Src/MoneyFox.Foundation/MoneyFox.Foundation.csproj
- Src/MoneyFox.Ios/MoneyFox.iOS.csproj
- Src/MoneyFox.Presentation/MoneyFox.Presentation.csproj
- Src/MoneyFox.ServiceLayer.Tests/MoneyFox.ServiceLayer.Tests.csproj
- Src/MoneyFox.ServiceLayer.Tests/Services/PaymentServiceTests.cs
- Src/MoneyFox.ServiceLayer/MoneyFox.ServiceLayer.csproj
- Src/MoneyFox.ServiceLayer/Services/PaymentService.cs
- Src/MoneyFox.Uwp.Business/MoneyFox.Uwp.Business.csproj
- Src/MoneyFox.Uwp.Tasks/MoneyFox.Uwp.Tasks.csproj
- Src/MoneyFox.Uwp/MoneyFox.Uwp.csproj
- Src/MoneyFox.Uwp/Views/EditAccountView.xaml
Issue: #
- Refactoring (no functional changes, no api changes) 
Update Nuget Packages.
- [C] Contains **NO** breaking changes
> Update nuget packages

- Src/MoneyFox.BusinessLogic/Backup/BackupManager.cs
- Src/MoneyFox.BusinessLogic/Backup/ICloudBackupService.cs
- Src/MoneyFox.BusinessLogic/Backup/OneDriveService.cs
- Src/MoneyFox.Uwp.Tasks/SyncBackupTask.cs
Issue: #
#1516 
- Bugfix 
the PromptType is set to DoNotPrompt which is supported in background task.
> fix background task on windows

- Src/MoneyFox.BusinessLogic/MoneyFox.BusinessLogic.csproj
- Src/MoneyFox.Foundation/MoneyFox.Foundation.csproj
- Src/MoneyFox.Presentation/MoneyFox.Presentation.csproj
- Src/MoneyFox.ServiceLayer/MoneyFox.ServiceLayer.csproj
- Src/MoneyFox.Uwp.Tasks/MoneyFox.Uwp.Tasks.csproj
- Src/MoneyFox.Uwp/MoneyFox.Uwp.csproj
Issue: #
- Bugfix 
Crahses on Startup on Windows
Starts correctly
> revert to MvvmCross 6.2.2

- Src/MoneyFox.Uwp.Tasks/SyncBackupTask.cs
Issue: #
#1525 
- Bugfix 
Timestamp is not set when tasks is finished on windows
Timestamp is set correctly now.
- [] Tested code on Android
> set timestamp

- Src/MoneyFox.Uwp/App.xaml.cs
Issue: #
- Bugfix
Crash on startup
startup correctly
> fix startup

- Src/MoneyFox.Ios/AppDelegate.cs
- Src/MoneyFox.ServiceLayer/Services/BackupService.cs
- Src/MoneyFox.ServiceLayer/ViewModels/AccountListViewModel.cs
> improve backup sync.

- Src/MoneyFox.Ios/Effects/PrimaryButtonEffect.cs
- Src/MoneyFox.Presentation/Effects/DeleteButtonEffect.cs
- Src/MoneyFox.Presentation/Effects/PrimaryButtonEffect.cs
- Src/MoneyFox.Presentation/Views/BackupPage.xaml
Issue: #
fix #1549 
fix #1548 
- Bugfix
see issues
spinner is shown and effects are applied.
> Several fixes

- Src/MoneyFox.Ios/AppDelegate.cs
- Src/MoneyFox.ServiceLayer/Services/PaymentService.cs
- Src/MoneyFox.ServiceLayer/ViewModels/AddAccountViewModel.cs
- Src/MoneyFox.ServiceLayer/ViewModels/AddPaymentViewModel.cs
- Src/MoneyFox.Uwp/App.xaml.cs
- Src/MoneyFox.Uwp/Style/AppStyles.xaml
- Src/MoneyFox.Uwp/Views/MainView.xaml
- Src/MoneyFox.Uwp/Views/MainView.xaml.cs
Issue: #
#1551 
#1469 
- Bugfix 
- Refactoring (no functional changes, no api changes) 
see issue
First item is selected.
Menu button is white as well
We use the UI kit now.
> Navigation view

- Src/MoneyFox.BusinessLogic/Backup/OneDriveService.cs
> only move if app folder is empty.

- Src/MoneyFox.Foundation/Resources/Strings.Designer.cs
- Src/MoneyFox.Foundation/Resources/Strings.de.resx
- Src/MoneyFox.Foundation/Resources/Strings.pl.resx
- Src/MoneyFox.Foundation/Resources/Strings.resx
- Src/MoneyFox.Foundation/Resources/Strings.zh-CN.resx
- Src/MoneyFox.Presentation/Views/BackupPage.xaml
> Adjust backup page text and updated translations

- Src/MoneyFox.Uwp/App.xaml.cs
- Src/MoneyFox.sln
Issue: #
- Bugfix 
In some cases there is a tile ID passed which is no number. So the app crashes.
We check if the tile ID is parseable.
> check if parseable.

- Src/MoneyFox.Uwp/MoneyFox.Uwp.csproj
> add 64 bit flag for test

- Src/MoneyFox.Migrations.Startup/MoneyFox.Migrations.Startup.csproj
- Src/MoneyFox.Uwp/App.xaml.cs
Issue: #
- Bugfix -->
If a tile id is present, not all initialization logic is executed.
the whole initialization is executed before the tile id is handeld.
> Improve logs and fix startup

- Src/MoneyFox.Android/MainApplication.cs
- Src/MoneyFox.BusinessDbAccess.Tests/MoneyFox.BusinessDbAccess.Tests.csproj
- Src/MoneyFox.BusinessLogic.Tests/MoneyFox.BusinessLogic.Tests.csproj
- Src/MoneyFox.BusinessLogic/Backup/BackupManager.cs
- Src/MoneyFox.BusinessLogic/MoneyFox.BusinessLogic.csproj
- Src/MoneyFox.DataLayer.Tests/MoneyFox.DataLayer.Tests.csproj
- Src/MoneyFox.Presentation.Tests/MoneyFox.Presentation.Tests.csproj
- Src/MoneyFox.ServiceLayer.Tests/MoneyFox.ServiceLayer.Tests.csproj
- Src/MoneyFox.Uwp/App.xaml.cs
Issue: #
- Bugfix 
When the user canceles the loggin the app crashes.
The exception is catched.
> catch exception

- Src/MoneyFox.BusinessLogic/Backup/OneDriveService.cs
- Src/MoneyFox.BusinessLogic/MoneyFox.BusinessLogic.csproj
- Src/MoneyFox.Ios/Entitlements.plist
- Src/MoneyFox.Ios/MoneyFox.iOS.csproj
- Src/MoneyFox.ServiceLayer.Tests/MoneyFox.ServiceLayer.Tests.csproj
Issue: #
- Bugfix 
msal can't write to keychain.
keychain access is granted.
> Fix ios onedrive login

- Src/MoneyFox.Android/Resources/values/colors.xml
- Src/MoneyFox.Android/Resources/values/styles.xml
- Src/MoneyFox.Presentation/App.xaml
- Src/MoneyFox.Presentation/Style/DarkTheme.xaml
- Src/MoneyFox.Presentation/Style/LightTheme.xaml
- Src/MoneyFox.Uwp/Style/ColorsDark.xaml
- Src/MoneyFox.Uwp/Style/ColorsLight.xaml
- Src/MoneyFox.Uwp/Style/ControlStyles.xaml
- Src/MoneyFox.Uwp/Views/BackupView.xaml
Issue: #
- Feature 
The color schemes are not optimal so far. This PR tries to improve that.
> Refreshed design

- Src/MoneyFox.Presentation/UserControls/ModifyPaymentUserControl.xaml
- Src/MoneyFox.Presentation/ViewModels/AddPaymentViewModel.cs
- Src/MoneyFox.Uwp/Style/ColorsDark.xaml
- Src/MoneyFox.Uwp/Style/ColorsLight.xaml
- Src/MoneyFox.Uwp/Views/AppShell.xaml
- Src/MoneyFox.Uwp/Views/UserControls/PaymentListUserControl.xaml
> Some fixes

- Src/MoneyFox.BusinessLogic.Tests/StatisticDataProvider/CashFlowProviderTests.cs
- Src/MoneyFox.BusinessLogic.Tests/StatisticDataProvider/CategorySpreadingProviderTests.cs
- Src/MoneyFox.BusinessLogic/StatisticDataProvider/CashFlowDataProvider.cs
- Src/MoneyFox.BusinessLogic/StatisticDataProvider/CategorySpreadingDataProvider.cs
Issue: #
#1626 
- Bugfix 
Charts do have special characters instead of the correct currency signs.
Currency signs are now correct added.
> Fix special character in chart

- Src/MoneyFox.Application.Tests/Statistics/Queries/GetCategorySummaryQueryTests.cs
- Src/MoneyFox.Application/Statistics/Queries/GetCategorySummary/GetCategeorySummaryQuery.cs
- Bugfix 
Category Summary shows an entry for each payment instead of one per category.
> fix multiple entries per category.

- Src/MoneyFox.Application/Payments/Queries/GetPaymentsForAccountId/GetPaymentsForAccountIdQuery.cs
Include Navigation Properties so that Categories and Recurring Payments are loaded.
> Include navigation properties

- Src/MoneyFox.Application/Accounts/Queries/GetAccounts/GetAccountsQuery.cs
> order accounts by name

- Src/MoneyFox.Application/Accounts/Queries/GetExcludedAccount/GetExcludedAccountQuery.cs
- Src/MoneyFox.Application/Accounts/Queries/GetIncludedAccount/GetIncludedAccountQuery.cs
> ordering by name.

- README.md
Just a README change, changed the first line to be more compelling :)
> Update README to sound more compelling

- Src/MoneyFox.Presentation/Views/BackgroundJobSettingsPage.xaml
Issue: #1602 
Enhancement
The backup sync interval in the settings menue is entered using an Entry
The backup sync interval is entered using a Stepper
> Replaced Entry with Stepper

- Src/MoneyFox.Android/Jobs/ClearPaymentsJob.cs
- Src/MoneyFox.Android/Jobs/RecurringPaymentJob.cs
- Src/MoneyFox.Android/Jobs/SyncBackupJob.cs
- Src/MoneyFox.Android/MainActivity.cs
- Src/MoneyFox.Android/Renderer/CustomEntryRenderer.cs
- Src/MoneyFox.Android/Renderer/CustomSearchBarRenderer.cs
- Src/MoneyFox.Application.Tests/Infrastructure/SqliteEfCoreContextFactory.cs
- Src/MoneyFox.Application.Tests/Payments/Commands/CreatePayment/CreatePaymentCommandTests.cs
- Src/MoneyFox.Application/Payments/Commands/CreatePayment/CreatePaymentCommand.cs
- Src/MoneyFox.BusinessLogic/Backup/IBackupManager.cs
- Src/MoneyFox.BusinessLogic/Backup/ICloudBackupService.cs
- Src/MoneyFox.Ios/AppDelegate.cs
- Src/MoneyFox.Presentation.Tests/Services/BackupServiceTests.cs
- Src/MoneyFox.Presentation.Tests/ViewModels/AddPaymentViewModelTests.cs
- Src/MoneyFox.Presentation.Tests/ViewModels/BackupViewModelTests.cs
- Src/MoneyFox.Presentation/Services/BackupService.cs
- Src/MoneyFox.Presentation/ViewModels/AccountListViewActionViewModel.cs
- Src/MoneyFox.Presentation/ViewModels/BackupViewModel.cs
- Src/MoneyFox.Presentation/ViewModels/EditAccountViewModel.cs
- Src/MoneyFox.Presentation/ViewModels/EditCategoryViewModel.cs
- Src/MoneyFox.Presentation/ViewModels/EditPaymentViewModel.cs
- Src/MoneyFox.Presentation/ViewModels/ModifyAccountViewModel.cs
- Src/MoneyFox.Presentation/ViewModels/ModifyCategoryViewModel.cs
- Src/MoneyFox.Presentation/ViewModels/ModifyPaymentViewModel.cs
- Src/MoneyFox.Presentation/ViewModels/PaymentListViewModel.cs
- Src/MoneyFox.Uwp.Tasks/SyncBackupTask.cs
> Improve dark theme

- Src/MoneyFox.Application.Tests/Payments/Commands/CreatePayment/CreatePaymentCommandTests.cs
- Src/MoneyFox.Presentation.Tests/ViewModels/AddPaymentViewModelTests.cs
- Src/MoneyFox.Presentation/ViewModels/AddCategoryViewModel.cs
- Src/MoneyFox.Presentation/ViewModels/AddPaymentViewModel.cs
- Src/MoneyFox.Uwp/Package.Appxmanifest
- Src/MoneyFox.Uwp/Views/UserControls/ModifyCategoryUserControl.xaml
> Fixes creation of categories and current balance calculation

- Src/MoneyFox.Ios/MoneyFox.iOS.csproj
- Src/MoneyFox.Presentation/ViewModels/EditPaymentViewModel.cs
> Fix navigation after delete payment

- Src/MoneyFox.Ios/MoneyFox.iOS.csproj
- Src/MoneyFox.Ios/Renderer/NavigationPageRenderer.cs
- Src/MoneyFox.Presentation/Views/SelectCategoryPage.xaml.cs
> ios modal sheet

- Src/MoneyFox.Uwp/Services/ActivationService.cs
- Src/MoneyFox.Uwp/Views/Settings/SettingsView.xaml
> fixes for background task

- Src/MoneyFox.Application/Common/CloudBackup/OneDriveService.cs
- Src/MoneyFox.Application/Common/RecurringPaymentHelper.cs
- Src/MoneyFox.Application/Payments/Commands/CreateRecurringPayments/CreateRecurringPaymentsCommand.cs
- Src/MoneyFox.Domain.Tests/Entities/RecurringPaymentTests.cs
- Src/MoneyFox.Domain/Entities/Payment.cs
- Src/MoneyFox.Domain/Entities/RecurringPayment.cs
- Src/MoneyFox.Migrations.Startup/EfCoreContextFactory.cs
- Src/MoneyFox.Migrations.Startup/MoneyFox.Migrations.Startup.csproj
- Src/MoneyFox.Persistence/Migrations/20200226165500_AddLastRecurrenceCreatedField.Designer.cs
- Src/MoneyFox.Persistence/Migrations/20200226165500_AddLastRecurrenceCreatedField.cs
- Src/MoneyFox.Presentation/ViewModels/BackupViewModel.cs
- Src/MoneyFox.Uwp/App.xaml.cs
- Src/MoneyFox.Uwp/BackgroundTasks/SyncBackupTask.cs
- Src/MoneyFox.Uwp/MoneyFox.Uwp.csproj
- Src/MoneyFox.Uwp/Package.Appxmanifest
- Src/MoneyFox.Uwp/Services/ActivationService.cs
- Src/MoneyFox.Uwp/ViewModels/BackupViewModel.cs
should fix #1250 besides several improvements and fixes for the backup
> Don't recreate recurring payments once deleted for the month

- README.md
> Added missed periods to readme.

- Src/MoneyFox.Uwp/Views/Dialogs/SelectDateRangeDialog.xaml
- Src/MoneyFox.Uwp/Views/PaymentListView.xaml
- Src/MoneyFox.Uwp/Views/UserControls/ModifyPaymentUserControl.xaml
Use CalendarDatePicker instead of the normal date picker.
> Change date picker

- Src/MoneyFox.Application/Common/CloudBackup/BackupService.cs
- Src/MoneyFox.Application/Common/CloudBackup/ICloudBackupService.cs
- Src/MoneyFox.Application/Common/CloudBackup/OneDriveService.cs
- Src/MoneyFox.Application/Common/CloudBackup/UserAccount.cs
- Src/MoneyFox.Ui.Shared/ViewModels/Backup/BackupViewModel.cs
- Src/MoneyFox.Uwp/Views/BackupView.xaml
- Src/MoneyFox/Views/Backup/BackupPage.xaml
Issue: #
https://github.com/MoneyFox/MoneyFox/issues/1560
Feature
No information is showed in backup view about logged user.
In mobile apps showing user's name and email centered under backup view header and title. In UWP app there is profile photo icon, user's name and email centered under view header. See attached images. I had problem with getting a profile photo of user. After research I found there might be some problems with it. Docs for Microsoft graph API shows example, that is working only for work or school accounts. So that's why I called it "partially done", there is problem with user profile photo but I kept default "no-photo" on UWP app.
- [ ✓ ] Tested code on Windows
- [ …
> Issue 1560 - partially done

- Src/MoneyFox/ViewModels/Statistics/StatisticCashFlowViewModel.cs
- Src/MoneyFox/ViewModels/Statistics/StatisticCategorySpreadingViewModel.cs
- Src/MoneyFox/Views/Statistics/StatisticSelectorPage.xaml
> #1910 color value label

- Src/MoneyFox.Application/Common/Constants/AppConstants.cs
- Src/MoneyFox.Uwp/Services/ActivationService.cs
- Src/MoneyFox.Uwp/Services/JumpListService.cs
- Src/MoneyFox.Uwp/Views/Payments/AddPaymentView.xaml.cs
> adjust shortcuts under windows

- Src/MoneyFox.Application.Tests/Statistics/Queries/GetCategorySpreadingQueryTests.cs
- Src/MoneyFox.Application/Statistics/Queries/GetCategorySpreadingQuery.cs
- Src/MoneyFox.Ui.Shared/ViewModels/Backup/BackupViewModel.cs
- Src/MoneyFox.Uwp/ViewModels/Statistic/StatisticCategorySpreadingViewModel.cs
- Src/MoneyFox.Uwp/Views/Categories/CategoryListView.xaml
- Src/MoneyFox.Uwp/Views/Payments/CategorySelectionControl.xaml
- Src/MoneyFox.Uwp/Views/Payments/ModifyPaymentUserControl.xaml
- Src/MoneyFox.Uwp/Views/Payments/PaymentListView.xaml
- Src/MoneyFox.Uwp/Views/Payments/PaymentListView.xaml.cs
- Src/MoneyFox.Uwp/Views/Statistics/StatisticCategorySpreadingView.xaml
- Src/MoneyFox.Uwp/Views/Statistics/StatisticCategorySpreadingView.xaml.cs
- Src/MoneyFox/ViewModels/Statistics/StatisticCategorySpreadingViewModel.cs
Also, refactor to flyout instead of dialog
> Add filter for number of categories

- Src/MoneyFox.Application/Common/CloudBackup/OneDriveService.cs
- Src/MoneyFox.Uwp/Services/StartupTasksService.cs
> catch auth issue on startup and logout then

- Src/MoneyFox.Application.Tests/Payments/Commands/DeletePaymentById/DeletePaymentByIdCommandTests.cs
- Src/MoneyFox.Application/Payments/Commands/DeletePaymentById/DeletePaymentByIdCommand.cs
- Src/MoneyFox.Domain/Exceptions/PaymentNotFoundException.cs
- Src/MoneyFox.Uwp/ViewModels/Payments/EditPaymentViewModel.cs
- Src/MoneyFox.Uwp/ViewModels/Payments/ModifyPaymentViewModel.cs
- Src/MoneyFox/ViewModels/Payments/EditPaymentViewModel.cs
> throw exception if no payment found

- Src/MoneyFox.Application/Payments/Commands/CreateRecurringPayments/CreateRecurringPaymentsCommand.cs
- Src/MoneyFox.Uwp/Services/StartupTasksService.cs
- Src/MoneyFox/ViewModels/Categories/CategoryListViewModel.cs
> Category dialog not opening on mobile 

- Src/MoneyFox.Application.Tests/Accounts/Queries/GetAccountNameById/GetAccountNameByIdQueryTests.cs
- Src/MoneyFox.Application/Accounts/Queries/GetAccountNameById/GetAccountNameByIdQuery.cs
> handle when account was not found

- Src/MoneyFox.Uwp/Src/DialogService.cs
> close all dialogs before showing a new one

- Src/MoneyFox.Uwp/ViewModels/Payments/PaymentListViewModel.cs
> fix nullpointer

- Src/MoneyFox.Application/CultureHelper.cs
- Src/MoneyFox.Ios/AppDelegate.cs
- Src/MoneyFox.Ios/IosModule.cs
- Src/MoneyFox.Tests/Converter/DecimalConverterTests.cs
- Src/MoneyFox/Converter/DecimalConverter.cs
- Src/MoneyFox/Views/Payments/ModifyPaymentContentView.xaml
> #2025 Try to fix decimal converter issues

- Src/MoneyFox.Ios/IosModule.cs
- Src/MoneyFox.Ui.Shared/ViewModels/Accounts/AccountViewModel.cs
> Fix locale issues

- Src/MoneyFox.Application.Tests/Statistics/Queries/GetCategoryProgressionHandlerTests.cs
- Src/MoneyFox.Application/Common/QueryObjects/PaymentQueryExtensions.cs
- Src/MoneyFox.Application/Resources/Strings.Designer.cs
- Src/MoneyFox.Application/Resources/Strings.resx
- Src/MoneyFox.Application/Statistics/Queries/GetCategoryProgressionQuery.cs
- Src/MoneyFox.Domain/DomainEnums.cs
- Src/MoneyFox.Uwp/MoneyFox.Uwp.csproj
- Src/MoneyFox.Uwp/Services/NavigationServiceInitializerService.cs
- Src/MoneyFox.Uwp/ViewModelLocator.cs
- Src/MoneyFox.Uwp/ViewModels/Statistic/StatisticCategoryProgressionViewModel.cs
- Src/MoneyFox.Uwp/ViewModels/Statistic/StatisticSelectorViewModel.cs
- Src/MoneyFox.Uwp/Views/Statistics/StatisticCategoryProgressionView.xaml
- Src/MoneyFox.Uwp/Views/Statistics/StatisticCategoryProgressionView.xaml.cs
- Src/MoneyFox/AppShell.xaml.cs
- Src/MoneyFox/Converter/NoCategorySelectedConverter.cs
- Src/MoneyFox/MoneyFox.csproj
- Src/MoneyFox/ViewModelLocator.cs
- Src/MoneyFox/ViewModels/Statistics/StatisticCategoryProgressionViewModel.cs
- Src/MoneyFox/ViewModels/Statistics/StatisticSelectorViewModel.cs
- Src/MoneyFox/Views/Payments/ModifyPaymentContentView.xaml
- Src/MoneyFox/Views/Statistics/StatisticCategoryProgressionPage.xaml
- Src/MoneyFox/Views/Statistics/StatisticCategoryProgressionPage.xaml.cs
> Category progression

- Src/MoneyFox.Uwp/MoneyFox.Uwp.csproj
Reverts MoneyFox/MoneyFox#2090
> Revert "remove single nutc"

- Src/MoneyFox.Ui.Shared/ViewModels/Payments/RecurringPaymentViewModel.cs
- Src/MoneyFox/ViewModels/Payments/ModifyPaymentViewModel.cs
> Fix default enddate

- Src/MoneyFox.Android/MainActivity.cs
- Src/MoneyFox.Android/MoneyFox.Android.csproj
- Src/MoneyFox.Ios/AppDelegate.cs
- Src/MoneyFox.Ios/MoneyFox.iOS.csproj
- Src/MoneyFox/MoneyFox.csproj
- Src/MoneyFox/Services/DialogService.cs
- Src/MoneyFox/ViewModels/DataBackup/BackupViewModel.cs
- Src/MoneyFox/Views/Dialogs/ConfirmMessageDialog.xaml
- Src/MoneyFox/Views/Dialogs/ConfirmMessageDialog.xaml.cs
- Src/MoneyFox/Views/Dialogs/DateSelectionPopup.xaml
- Src/MoneyFox/Views/Dialogs/DateSelectionPopup.xaml.cs
- Src/MoneyFox/Views/Dialogs/FilterPopup.xaml
- Src/MoneyFox/Views/Dialogs/FilterPopup.xaml.cs
- Src/MoneyFox/Views/Dialogs/LoadingDialog.xaml
- Src/MoneyFox/Views/Dialogs/LoadingDialog.xaml.cs
- Src/MoneyFox/Views/Dialogs/MessageDialog.xaml
- Src/MoneyFox/Views/Dialogs/MessageDialog.xaml.cs
due to lack of popups with transparent background on ios.
> Revert replacement of rgpopup

- Src/MoneyFox.Infrastructure/DataAccess/CategoryRepository.cs
- Src/MoneyFox.Infrastructure/InfrastructureModule.cs
> fix issue with category creation

- Src/MoneyFox.Win/MoneyFox.Win/App.xaml.cs
- Src/MoneyFox.Win/MoneyFox.Win/MainWindow.xaml.cs
> sync on startup and closing for windows

- Src/MoneyFox.Core/ApplicationCore/Domain/Aggregates/AccountAggregate/Account.cs
- Src/MoneyFox.Core/ApplicationCore/Queries/Statistics/GetCategorySummary/GetCategeorySummaryQuery.cs
- Src/MoneyFox.Win.Infrastructure/Adapters/BrowserAdapter.cs
- Src/MoneyFox.Win.Infrastructure/Preferences.winui.cs
- Src/MoneyFox/ViewModels/Accounts/AccountViewModel.cs
- Src/MoneyFox/ViewModels/Payments/PaymentListViewModel.cs
Issue: #None
- Bugfix
- Refactoring (no functional changes, no api changes)
Build successful
Build successful. Improve code security and fixed minor bugs.
> Improve code security

- pipelines/azure-pipelines-android.yml
- pipelines/azure-pipelines-winui.yml
Reverts MoneyFox/MoneyFox#2473
> Revert "Update dependency CopyFiles to v2.211.0"

- pipelines/azure-pipelines-android.yml
- pipelines/azure-pipelines-iOS.yml
- pipelines/azure-pipelines-winui.yml
Reverts MoneyFox/MoneyFox#2481
> Revert "Update dependency PublishBuildArtifacts to v1.211.0"

- pipelines/azure-pipelines-android.yml
Reverts MoneyFox/MoneyFox#2478
> Revert "Update dependency JavaToolInstaller to v0.211.0"

- pipelines/azure-pipelines-iOS.yml
Reverts MoneyFox/MoneyFox#2502
> Revert "Update dependency InstallAppleProvisioningProfile to v1.212.0"

- pipelines/azure-pipelines-iOS.yml
Reverts MoneyFox/MoneyFox#2501
> Revert "Update dependency InstallAppleCertificate to v2.212.0"

- CONTRIBUTING.md
Issue: #
Documentation content changes -->
> Fix typo on line 7 and 10

- Src/MoneyFox.Ui/ViewModels/Payments/AddPaymentViewModel.cs
- Src/MoneyFox.Ui/Views/Accounts/AccountListPage.xaml
- Src/MoneyFox.Ui/Views/Accounts/AccountViewModel.cs
- Src/MoneyFox.Ui/Views/Accounts/EditAccountPage.xaml
- Src/MoneyFox.Ui/Views/Accounts/EditAccountPage.xaml.cs
- Src/MoneyFox.Ui/Views/Accounts/EditAccountViewModel.cs
- Src/MoneyFox.Ui/Views/Accounts/ModifyAccountViewModel.cs
- Src/MoneyFox.Ui/Views/Categories/CategoryListPage.xaml
- Src/MoneyFox.Ui/Views/Categories/ModifyCategoryContentView.xaml
Issue: #2546 
This fixes several issues with swipe view and editing accounts.
- Bugfix
> Edit account page

- Src/MoneyFox.Ui/Platforms/iOS/Program.cs
- Src/MoneyFox.Ui/Views/Budget/AddBudgetPage.xaml
- Src/MoneyFox.Ui/Views/Budget/AddBudgetPage.xaml.cs
- Src/MoneyFox.Ui/Views/Budget/EditBudgetPage.xaml
- Src/MoneyFox.Ui/Views/Budget/ModifyBudgetView.xaml
Issue: #2550
- Bugfix
Budgetpages have now a proper height.
> Fix scrolling on budget modification

- Src/MoneyFox.Core/Interfaces/IBrowserAdapter.cs
- Src/MoneyFox.Core/Interfaces/IEmailAdapter.cs
- Src/MoneyFox.Ui.Tests/ViewModels/AboutViewModelTests.cs
- Src/MoneyFox.Ui/Infrastructure/Adapters/BrowserAdapter.cs
- Src/MoneyFox.Ui/MoneyFox.Ui.csproj
- Src/MoneyFox.Ui/Platforms/Android/AndroidManifest.xml
- Src/MoneyFox.Ui/Views/About/AboutViewModel.cs
> Fix opening urls

- Src/MoneyFox.Ui/AppShell.xaml
- Src/MoneyFox.Ui/Controls/Card.cs
- Src/MoneyFox.Ui/Resources/Styles/Styles.xaml
- Src/MoneyFox.Ui/Views/Dashboard/DashboardPage.xaml
- Src/MoneyFox.Ui/Views/Payments/ModifyPaymentContentView.xaml
Issue: #
Less blurry images on ios.
Less aggressive shadows on ios.
> Fix small design issues

- Src/MoneyFox.Core.Tests/ApplicationCore/Queries/LoadBudgetEntryTests.cs
- Src/MoneyFox.Core.Tests/ApplicationCore/Queries/LoadBudgetListDataTests.cs
- Src/MoneyFox.Core.Tests/ApplicationCore/UseCases/CreateBudgetShould.cs
- Src/MoneyFox.Core.Tests/ApplicationCore/UseCases/UpdateBudgetShould.cs
- Src/MoneyFox.Core.Tests/Domain/Aggregates/BudgetAggregate/BudgetShould.cs
- Src/MoneyFox.Core.Tests/Domain/Aggregates/BudgetAggregate/BudgetTests.cs
- Src/MoneyFox.Core.Tests/TestFramework/BudgetAssertion.cs
- Src/MoneyFox.Core.Tests/TestFramework/TestData.Budget.cs
- Src/MoneyFox.Core/ApplicationCore/Queries/BudgetEntryLoading/BudgetEntryData.cs
- Src/MoneyFox.Core/ApplicationCore/Queries/BudgetEntryLoading/LoadBudgetEntry.cs
- Src/MoneyFox.Core/ApplicationCore/Queries/BudgetListLoading/BudgetListData.cs
- Src/MoneyFox.Core/ApplicationCore/Queries/BudgetListLoading/LoadBudgetListData.cs
- Src/MoneyFox.Ui.Tests/ViewModels/Budget/AddBudgetViewModelTests.cs
- Src/MoneyFox.Ui.Tests/ViewModels/Budget/BudgetListPageViewModelTests.cs
- Src/MoneyFox.Ui.Tests/ViewModels/Budget/EditBudgetViewModelTests.cs
- Src/MoneyFox.Ui/Views/Budget/EditBudgetViewModel.cs
> Fix picker assignment for budget modification

- Src/MoneyFox.Ui.Tests/ViewModels/Budget/AddBudgetViewModelTests.cs
- Src/MoneyFox.Ui.Tests/ViewModels/Budget/EditBudgetViewModelTests.cs
- Src/MoneyFox.Ui/Views/Budget/AddBudgetViewModel.cs
- Src/MoneyFox.Ui/Views/Budget/EditBudgetViewModel.cs
> Improve validation for budget

- Src/MoneyFox.Ui/InversionOfControl/MoneyFoxConfig.cs
- Src/MoneyFox.Ui/ViewModels/Payments/AddPaymentViewModel.cs
- Src/MoneyFox.Ui/ViewModels/Payments/EditPaymentViewModel.cs
- Src/MoneyFox.Ui/ViewModels/Payments/ModifyPaymentViewModel.cs
> 2642 cant edit a existing payment with a recurring payment

- Src/MoneyFox.Ui/Views/Accounts/AccountListPage.xaml
- Src/MoneyFox.Ui/Views/Accounts/AccountListPage.xaml.cs
> rearrange tap gesture recognizer

- Src/MoneyFox.Ui/Views/Accounts/DesktopAccountListPage.xaml
- Src/MoneyFox.Ui/Views/Dashboard/DashboardPage.xaml
Issue: #2596
- Bugfix 
There is no way to edit a account
there is a context menu in the account list page.
> 2596 swipeview control throws a systemaccessviolationexception in windows

- Src/MoneyFox.Ui/Views/About/AboutPage.xaml
> Fix binding in about page

- Src/MoneyFox.Ui/Views/SetupAssistant/SetupCompletionViewModel.cs
- Src/MoneyFox.Ui/Views/SetupAssistant/WelcomeViewModel.cs
> don't reassign mainpage and just navigate to dashboard

- Src/MoneyFox.Ui/Controls/CustomDatePicker.xaml.cs
> 2727-customdatepicker-causes-endless-loop-on-windows

- Src/MoneyFox.Ui/App.xaml.cs
- Src/MoneyFox.Ui/Views/About/AboutViewModel.cs
- Src/MoneyFox.Ui/Views/Accounts/AccountListPage.xaml.cs
- Src/MoneyFox.Ui/Views/Accounts/AccountListViewModel.cs
- Src/MoneyFox.Ui/Views/Accounts/DesktopAccountListPage.xaml.cs
- Src/MoneyFox.Ui/Views/Accounts/ModifyAccountViewModel.cs
- Src/MoneyFox.Ui/Views/Backup/BackupViewModel.cs
- Src/MoneyFox.Ui/Views/BasePageViewModel.cs
- Src/MoneyFox.Ui/Views/Budget/BudgetListViewModel.cs
- Src/MoneyFox.Ui/Views/Budget/ModifyBudgetViewModel.cs
- Src/MoneyFox.Ui/Views/Categories/CategoryListViewModel.cs
- Src/MoneyFox.Ui/Views/Categories/ModifyCategory/ModifyCategoryViewModel.cs
- Src/MoneyFox.Ui/Views/Dashboard/DashboardViewModel.cs
- Src/MoneyFox.Ui/Views/OverflowMenu/OverflowMenuViewModel.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentListPage.xaml.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentListViewModel.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentModification/ModifyPaymentViewModel.cs
- Src/MoneyFox.Ui/Views/Popups/SelectDateRangeDialogViewModel.cs
- Src/MoneyFox.Ui/Views/Popups/SelectFilterDialogViewModel.cs
- Src/MoneyFox.Ui/Views/Settings/SettingsViewModel.cs
- Src/MoneyFox.Ui/Views/SetupAssistant/CategoryIntroductionViewModel.cs
- Src/MoneyFox.Ui/Views/SetupAssistant/SetupCompletionViewModel.cs
- Src/MoneyFox.Ui/Views/SetupAssistant/WelcomeViewModel.cs
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/PaymentForCategoryListViewModel.cs
- Src/MoneyFox.Ui/Views/Statistics/Selector/StatisticSelectorViewModel.cs
- Src/MoneyFox.Ui/Views/Statistics/StatisticViewModel.cs
> Move to i recipient

- Src/MoneyFox.Ui/Views/Accounts/AccountListPage.xaml
> fix scrolling by using a grid, adjust header alignment

- .github/workflows/validate-pullrequest.yml
> only install necessary workloads

- pipelines/azure-pipelines-android.yml
- pipelines/azure-pipelines-iOS.yml
- pipelines/azure-pipelines-winui.yml
> up-version

- Src/MoneyFox.Ui/Views/Accounts/AccountModification/ModifyAccountViewModel.cs
- Src/MoneyFox.Ui/Views/Budget/BudgetModification/AddBudgetViewModel.cs
- Src/MoneyFox.Ui/Views/Budget/BudgetModification/EditBudgetViewModel.cs
- Src/MoneyFox.Ui/Views/Categories/CategorySelection/CategorySelectionViewModel.cs
- Src/MoneyFox.Ui/Views/Categories/ModifyCategory/ModifyCategoryViewModel.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentModification/ModifyPaymentViewModel.cs
> first navigate and then send the message

- Src/MoneyFox.Ui/Views/Accounts/AccountModification/ModifyAccountContentView.xaml.cs
> Skip compilation to prevent data binding issue

- Src/MoneyFox.Ui/Views/Accounts/AccountList/AccountListViewModel.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentList/PaymentListViewModel.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentModification/ModifyPaymentViewModel.cs
> set IsActive to true in init

- Src/MoneyFox.Ui/App.xaml.cs
> use WeakReferenceMessenger instead of try getting it from DI

- Src/MoneyFox.Ui/Platforms/iOS/Utils/Extensions.cs
> fix crash in release mode

- Src/MoneyFox.Ui/Views/Budget/BudgetListPage.xaml
> make button not overlap text

- Src/MoneyFox.Ui/Views/Payments/PaymentModification/AddPaymentViewModel.cs
> only set selected charged account on first load

- .github/workflows/validate-pullrequest.yml
- pipelines/azure-pipelines-android.yml
- pipelines/azure-pipelines-iOS.yml
- pipelines/azure-pipelines-winui.yml
> set fix version

- Src/MoneyFox.Ui/App.xaml.cs
> execute clear and check recurring payments despite backup exception

- Src/MoneyFox.Ui/App.xaml.cs
- Src/MoneyFox.Ui/AppShell.xaml
- Src/MoneyFox.Ui/AppShell.xaml.cs
- Src/MoneyFox.Ui/AppShellDesktop.xaml
- Src/MoneyFox.Ui/Views/Setup/SetupCompletionViewModel.cs
- Src/MoneyFox.Ui/Views/Setup/SetupShell.xaml
- Src/MoneyFox.Ui/Views/Setup/SetupShell.xaml.cs
> 2802 rework how setup is shown

- Src/MoneyFox.Ui/AppShellDesktop.xaml
> 2800-menu-icons-on-windows-in-light-mode-white

- Src/MoneyFox.Core/Common/ParallelNoWaitPublisher.cs
- Src/MoneyFox.Core/InversionOfControl/CoreConfig.cs
- Src/MoneyFox.Core/MoneyFox.Core.csproj
> 2824 saving a payment takes a very long time

- Src/MoneyFox.Ui/Views/Backup/BackupPage.xaml
> use avatar view to display profile picture

- Src/MoneyFox.Ui/Platforms/Android/AndroidManifest.xml
> add version tag back to android manifest

- Src/MoneyFox.Ui/Views/Setup/SetupShell.xaml.cs
>  2840 add missing routes

- Src/MoneyFox.Ui/Views/Accounts/AccountList/AccountListPage.xaml
- Src/MoneyFox.Ui/Views/Categories/CategoryListPage.xaml
- Src/MoneyFox.Ui/Views/Categories/CategorySelection/SelectCategoryPage.xaml
> Readd deemphasize on future payments

- Src/MoneyFox.Ui/Views/Payments/PaymentList/DateGroupCardOpacityConverter.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentList/PaymentListPage.xaml
> readd deemphasize

- Src/MoneyFox.Ui/Views/Categories/CategoryListPage.xaml
- Src/MoneyFox.Ui/Views/OverflowMenu/OverflowMenuPage.xaml
- Src/MoneyFox.Ui/Views/Payments/PaymentList/PaymentListPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/PaymentForCategoryListPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/StatisticCategorySummaryPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/Selector/StatisticSelectorPage.xaml
> Fix linker issue with paymentlist

- Src/MoneyFox.Ui/Views/Payments/PaymentList/PaymentListPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/PaymentForCategoryListPage.xaml
> truncate category name

- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/StatisticCategorySummaryPage.xaml
> Improve alignment

- global.json
> add global.json

- Src/MoneyFox.Ui/Views/Payments/PaymentModification/EditPaymentViewModel.cs
- Src/MoneyFox.Ui/Views/Payments/RecurringPaymentViewModel.cs
> fix recurrence not being loaded correctly

- Src/MoneyFox.Ui/AppShell.xaml
> 2695 revert selected tab is not highlighted on ios

- .github/workflows/validate-pullrequest.yml
- pipelines/azure-pipelines-android.yml
- pipelines/azure-pipelines-iOS.yml
- pipelines/azure-pipelines-winui.yml
Issue: #
- Build or CI related changes
> update .net version

- Src/MoneyFox.Ui/Views/Payments/PaymentList/PaymentListPage.xaml
Issue: #2878  #2875 
- Bugfix 
> 2878 texts in paymentlist sometimes cut off

- Src/MoneyFox.Ui/Resources/Strings/Translations.ar.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.bg.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.cs.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.da.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.de.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.el.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.es.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.et.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.fi.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.fr.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.id.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.it.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.ja.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.lt.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.nl.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.no.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.pl.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.pt.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.ro.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.ru.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.sk.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.sv.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.tr.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.uk.resx
- Src/MoneyFox.Ui/Resources/Strings/Translations.zh-CN.resx
- Src/MoneyFox.Ui/Views/Dashboard/DashboardPage.xaml
- Src/MoneyFox.Ui/Views/Payments/PaymentList/PaymentListPage.xaml
Issue: #
- Bugfix 
Accounts are displayed too large on iOS
> fix layout on ios

- .github/workflows/validate-pullrequest.yml
- pipelines/azure-pipelines-android.yml
- pipelines/azure-pipelines-iOS.yml
- pipelines/azure-pipelines-winui.yml
> update to new dotnet version

- Src/MoneyFox.Ui/Controls/Search.xaml
> make searchbox on windows nicer

- Src/MoneyFox.Core.Tests/MoneyFox.Core.Tests.csproj
- Src/MoneyFox.Core.Tests/Queries/LoadBudgetDataForListTests.cs
- Src/MoneyFox.Core.Tests/Queries/LoadBudgetListDataTests.cs
- Src/MoneyFox.Core/MoneyFox.Core.csproj
- Src/MoneyFox.Core/Queries/BudgetList/BudgetData.cs
- Src/MoneyFox.Core/Queries/BudgetList/LoadBudgetDataForList.cs
- Src/MoneyFox.Domain.Tests/TestFramework/TestData.Budget.cs
- Src/MoneyFox.Ui.Tests/Views/Budget/BudgetListPageViewModelTests.cs
- Src/MoneyFox.Ui/Platforms/iOS/Utils/Extensions.cs
- Src/MoneyFox.Ui/Views/Budget/BudgetListItemViewModel.cs
- Src/MoneyFox.Ui/Views/Budget/BudgetListViewModel.cs
- Src/MoneyFox.Ui/Views/Categories/CategorySelection/SelectCategoryViewModel.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentModification/AddPaymentViewModel.cs
- Src/MoneyFox.Ui/Views/Setup/SelectCurrency/SetupCurrencyViewModel.cs
> 2894 monthly budget in budget list is not calculated correctly

- Src/MoneyFox.Ui/Views/Budget/BudgetListPage.xaml
- Src/MoneyFox.Ui/Views/Dashboard/DashboardPage.xaml
> fix progress bars for budgets

- Src/MoneyFox.Ui/Controls/AmountEntry.xaml.cs
> 2806 text in amount entry is not preselected when entry gets focus

- Src/MoneyFox.Ui/Views/Statistics/CashFlow/StatisticCashFlowViewModel.cs
- Src/MoneyFox.Ui/Views/Statistics/CategoryProgression/StatisticCategoryProgressionViewModel.cs
- Src/MoneyFox.Ui/Views/Statistics/CategorySpreading/StatisticCategorySpreadingViewModel.cs
- Src/MoneyFox.Ui/Views/Statistics/MonthlyAccountCashFlow/StatisticAccountMonthlyCashflowViewModel.cs
> Fix livechart warnings

- Src/MoneyFox.Ui/MoneyFox.Ui.csproj
- Src/MoneyFox.Ui/Views/Accounts/AccountList/AccountListPage.xaml
- Src/MoneyFox.Ui/Views/Accounts/AccountList/AccountListPage.xaml.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentList/PaymentListPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/PaymentForCategoryListPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/StatisticCategorySummaryViewModel.cs
> Fix category summary list

- Src/MoneyFox.Ui/Views/Statistics/Selector/StatisticSelectorPage.xaml
> add workaround

- Src/MoneyFox.Ui/MoneyFox.Ui.csproj
> revert maui version

- Src/MoneyFox.Ui/Resources/Strings/Translations.Designer.cs
- Src/MoneyFox.Ui/Resources/Strings/Translations.resx
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/PaymentDayGroup.cs
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/PaymentForCategoryListPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/PaymentForCategoryListViewModel.cs
> Invert order in category summary and add expense and revenue

- Src/MoneyFox.Core.Tests/stryker-config.json
- Src/MoneyFox.Ui.Tests/Views/Statistics/CategorySummary/PaymentDayGroupTests.cs
- Src/MoneyFox.Ui.Tests/Views/Statistics/CategorySummary/PaymentForCategoryListViewModelTests.cs
- Src/MoneyFox.Ui/Resources/Strings/Translations.Designer.cs
- Src/MoneyFox.Ui/Resources/Strings/Translations.resx
- Src/MoneyFox.Ui/Views/Categories/CategoryGroup.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentList/PaymentListPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/PaymentDayGroup.cs
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/PaymentForCategoryListPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/PaymentForCategoryListViewModel.cs
- Src/MoneyFox.Ui/Views/Statistics/Selector/StatisticSelectorPage.xaml
> Add revenue and expense to payment for category

- Src/MoneyFox.Ui.Tests/Views/Payments/EditPaymentViewModelTests.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentModification/EditPaymentViewModel.cs
- Src/MoneyFox.Ui/Views/Payments/RecurringPaymentViewModel.cs
> Fix recurrence in edit payment

- Src/MoneyFox.Ui/Views/Budget/BudgetListPage.xaml
> workaround for header

- Src/MoneyFox.Ui.Tests/Views/Budget/AddBudgetViewModelTests.cs
- Src/MoneyFox.Ui/Views/Accounts/AccountModification/EditAccountViewModel.cs
- Src/MoneyFox.Ui/Views/Accounts/AccountModification/ModifyAccountViewModel.cs
- Src/MoneyFox.Ui/Views/Budget/BudgetModification/AddBudgetViewModel.cs
- Src/MoneyFox.Ui/Views/Budget/BudgetModification/EditBudgetViewModel.cs
- Src/MoneyFox.Ui/Views/Budget/BudgetModification/ModifyBudgetViewModel.cs
- Src/MoneyFox.Ui/Views/Categories/ModifyCategory/ModifyCategoryViewModel.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentModification/EditPaymentViewModel.cs
> 2914 after renaming an account the loading screen does not disappear

- Src/MoneyFox.Ui/Views/Statistics/CashFlow/StatisticCashFlowPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/CategorySpreading/StatisticCategorySpreadingPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/CategorySummary/StatisticCategorySummaryPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/StatisticViewModel.cs
> adjust arrangement of charts

- Src/MoneyFox.Ui/Controls/AccountPicker/AccountPicker.xaml
- Src/MoneyFox.Ui/MoneyFox.Ui.csproj
> Update maui version

- .github/workflows/build.yml
Issue: #
- Build or CI related changes
> new github workflow file

- Src/MoneyFox.Infrastructure.Tests/MoneyFox.Infrastructure.Tests.csproj
Issue: #
- Refactoring (no functional changes, no api changes) 
remove leftover reference
> remove moq reference

- Src/MoneyFox.Ui/App.xaml.cs
- Src/MoneyFox.Ui/AppCenterOption.cs
- Src/MoneyFox.Ui/MoneyFox.Ui.csproj
> remove appcenter reference

- Src/MoneyFox.Infrastructure/Persistence/Configurations/AccountConfiguration.cs
- Src/MoneyFox.Infrastructure/Persistence/Configurations/BudgetConfiguration.cs
- Src/MoneyFox.Infrastructure/Persistence/Configurations/CategoryConfiguration.cs
- Src/MoneyFox.Infrastructure/Persistence/Configurations/PaymentConfiguration.cs
- Src/MoneyFox.Infrastructure/Persistence/Configurations/RecurringPaymentConfiguration.cs
- Src/MoneyFox.Infrastructure/Persistence/Configurations/RecurringTransactionConfiguration.cs
- Src/MoneyFox.Infrastructure/Persistence/Migrations/20230901231931_AddUniqueConstraints.Designer.cs
- Src/MoneyFox.Infrastructure/Persistence/Migrations/20230901231931_AddUniqueConstraints.cs
- Src/MoneyFox.Ui/App.xaml.cs
> Add unique constraint for ids

- Src/MoneyFox.Core.Tests/Features/TransactionRecurrence/CheckTransactionRecurrence.cs
- Src/MoneyFox.Core/Common/Extensions/RecurringTransactionExtensions.cs
- Src/MoneyFox.Core/Common/Settings/SettingConstants.cs
- Src/MoneyFox.Core/Common/Settings/SettingsFacade.cs
- Src/MoneyFox.Core/Features/TransactionRecurrence/CheckTransactionRecurrence.cs
> Fix issues with recurring payment migration and with enddate validation

- Src/MoneyFox.Ui/MoneyFox.Ui.csproj
- Src/MoneyFox.Ui/Views/Statistics/CategorySpreading/StatisticCategorySpreadingViewModel.cs
> Chart fixes

- Src/MoneyFox.Ui/App.xaml.cs
> catch migration exceptions

- Src/MoneyFox.Ui/MoneyFox.Ui.csproj
Reverts MoneyFox/MoneyFox#3068
> Revert "Update dependency CommunityToolkit.Maui to v6"

- Src/MoneyFox.Ui/Views/Statistics/CategoryProgression/StatisticCategoryProgressionViewModel.cs
- Src/MoneyFox.Ui/Views/Statistics/MonthlyAccountCashFlow/StatisticAccountMonthlyCashflowViewModel.cs
> Minor imporvments for charts

- Src/Migration/Migration.csproj
- Src/MoneyFox.Ui/AppShell.xaml
- Src/MoneyFox.Ui/Platforms/iOS/Renderer/CustomShellRenderer.cs
- Src/MoneyFox.Ui/Views/Categories/CategoryListPage.xaml
- Src/MoneyFox.Ui/Views/Dashboard/DashboardPage.xaml
- Src/MoneyFox.Ui/Views/Settings/SettingsViewModel.cs
> Fix ios issues after package upgrade

- .github/workflows/validate-pullrequest.yml
- pipelines/azure-pipelines-iOS.yml
> Set app code version

- .github/workflows/validate-pullrequest.yml
- pipelines/azure-pipelines-iOS.yml
> Change macos build agent to arm

- Src/MoneyFox.Ui/MoneyFox.Ui.csproj
> use released .net maui version

- pipelines/azure-pipelines-iOS.yml
> Change set appcode version

- pipelines/azure-pipelines-iOS.yml
Reverts MoneyFox/MoneyFox#3115
> Revert "Change macos build agent to arm"

- Src/MoneyFox.Ui/Views/Budget/BudgetListPage.xaml
> fix crash on budget list

- Src/MoneyFox.Ui/Views/Payments/PaymentModification/AddPaymentViewModel.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentModification/EditPaymentViewModel.cs
> call base method properly

- pipelines/azure-pipelines-winui.yml
> use new certificate

- pipelines/azure-pipelines-winui.yml
Issue: #
- Build or CI related changes
> adjust pipeline to set certificate infos from variables

- Src/MoneyFox.Ui/Common/Navigation/NavigationService.cs
> fix navigation tracking

- .github/workflows/build.yml
> set certificate in csproj

- Src/MoneyFox.Ui/Views/Setup/WelcomeViewModel.cs
> add missing step to setup

- pipelines/azure-pipelines-android.yml
> use java 17

- Src/MoneyFox.Ui/Views/Setup/SelectCurrency/SetupCurrencyPage.xaml
> adjust row size

- Src/MoneyFox.Ui/Views/Budget/BudgetListViewModel.cs
> fix monthly spending in budget list not showing

- Src/MoneyFox.Core.Tests/Queries/GetPaymentsInBudgetTests.cs
- Src/MoneyFox.Core/Queries/GetPaymentsInBudget.cs
- Src/MoneyFox.Ui/Views/Budget/BudgetOverview/BudgetOverviewPage.xaml
- Src/MoneyFox.Ui/Views/Budget/BudgetOverview/BudgetOverviewViewModel.cs
- Src/MoneyFox.Ui/Views/Budget/BudgetOverview/BudgetPaymentViewModel.cs
> add note to budget overview

- Src/MoneyFox.Domain.Tests/TestFramework/TestPaymentDbExtensions.cs
- Src/MoneyFox.Ui/MoneyFox.Ui.csproj
- Src/MoneyFox.Ui/Views/Accounts/AccountModification/AccountViewModel.cs
- Src/MoneyFox.Ui/Views/Accounts/AccountModification/AddAccountPage.xaml
- Src/MoneyFox.Ui/Views/Accounts/AccountModification/EditAccountViewModel.cs
- Src/MoneyFox.Ui/Views/Budget/BudgetListPage.xaml
- Src/MoneyFox.Ui/Views/Budget/BudgetOverview/BudgetOverviewPage.xaml
- Src/MoneyFox.Ui/Views/Budget/BudgetOverview/BudgetOverviewViewModel.cs
- Src/MoneyFox.Ui/Views/Budget/BudgetOverview/BudgetPaymentViewModel.cs
- Src/MoneyFox.Ui/Views/Categories/ModifyCategory/CategoryViewModel.cs
- Src/MoneyFox.Ui/Views/Categories/ModifyCategory/ModifyCategoryViewModel.cs
- Src/MoneyFox.Ui/Views/Payments/PaymentList/PaymentListPage.xaml
> order payments on budget overview and simplify some xaml

- Src/MoneyFox.Ui/App.xaml.cs
- Src/MoneyFox.Ui/DefaultNavigationPage.cs
> Fix issue with separator

- Src/MoneyFox.Ui/Views/Payments/PaymentModification/AddPaymentPage.xaml
- Src/MoneyFox.Ui/Views/Payments/PaymentModification/EditPaymentPage.xaml
- Src/MoneyFox.Ui/Views/Payments/PaymentModification/ModifyPaymentViewModel.cs
> fix binding
