MoneyFox/MoneyFox

- Src/MoneyManager.Windows/AppShell.xaml.cs
Back button does not need to be explicitly hidden for tablet mode and phones as it done automatically.
> Deleted unnecessary explicit hiding of back button

- Src/MoneyManager.Windows/AppShell.xaml.cs
Back button is now collapsed when the navigation stack is empty i.e.
there's no page to go back to. Issue #619
> Back button can now hide

- Src/MoneyManager.Windows/AppShell.xaml
- Src/MoneyManager.Windows/AppShell.xaml.cs
- Src/MoneyManager.Windows/Views/MainView.xaml
- Src/MoneyManager.Windows/Views/SettingsView.xaml
- Src/MoneyManager.Windows/Views/StatisticsView.xaml
The splitview pane is now made of two listviews, top and bottom. Code had to be reworked to support having two listviews. Command bars have been moved from root page to their own grid row so that they no longer go over the splitview. #618
> Seperated splitview pane to top and bottom parts

- Src/MoneyFox.Windows/Views/AboutView.xaml
- Src/MoneyFox.Windows/Views/ModifyAccountView.xaml
- Src/MoneyFox.Windows/Views/ModifyPaymentView.xaml
- Src/MoneyFox.Windows/Views/StatisticCategorySummaryView.xaml
- Src/MoneyFox.Windows/Views/UserControls/CategoryListUserControl.xaml
Fixed issue #751, scrollbars are shown only if the content exceeds the page's margins.
> Scrollbars automatically hidden

- Src/MoneyFox.Windows/Views/UserControls/AccountListUserControl.xaml.cs
- Src/MoneyFox.Windows/Views/UserControls/CategoryListUserControl.xaml.cs
Updated menu's to now use MenuFlyout instead of just FlyoutBase. This allows ShowAt() to have a relative position (The mouse cursor location) to the actual senderElement.
> #699 ContextMenu Enhancement

- Src/MoneyFox.Business/ViewModels/ModifyPaymentViewModel.cs
if the user adds a value with the negative operator when creating a new expense or income, the program will handle the value without the use of the operator.
> bugFix for issue #1052,

- Src/MoneyFox.Windows/Views/AccountListView.xaml
The height property was preventing the command bar from fully opening. Tested on Windows 10 and Windows 10 Mobile.
This resolves #1162
> Fix Command bar in windows

- Src/MoneyFox.Business/ViewModels/AboutViewModel.cs
Fixed the link going to the GitHub Contributions page. This fixes issue #1164
> Fixed Link to Contributions Page

- Src/MoneyFox.Uwp/Views/AddAccountView.xaml
- Src/MoneyFox.Uwp/Views/AddCategoryView.xaml
- Src/MoneyFox.Uwp/Views/AddPaymentView.xaml
- Src/MoneyFox.Uwp/Views/CategoryListView.xaml
- Src/MoneyFox.Uwp/Views/EditAccountView.xaml
- Src/MoneyFox.Uwp/Views/EditCategoryView.xaml
- Src/MoneyFox.Uwp/Views/EditPaymentView.xaml
- Src/MoneyFox.Uwp/Views/LoginView.xaml
- Src/MoneyFox.Uwp/Views/PaymentListView.xaml
- Src/MoneyFox.Uwp/Views/SelectCategoryListView.xaml
- Src/MoneyFox.Uwp/Views/SettingsView.xaml
- Src/MoneyFox.Uwp/Views/StatisticCashFlowView.xaml
- Src/MoneyFox.Uwp/Views/StatisticCategorySpreadingView.xaml
- Src/MoneyFox.Uwp/Views/StatisticCategorySummaryView.xaml
- Src/MoneyFox.Uwp/Views/StatisticSelectorView.xaml
- Src/MoneyFox.Uwp/Views/UserControls/AboutUserControl.xaml
- Src/MoneyFox.Uwp/Views/UserControls/BalanceUserControl.xaml
- Src/MoneyFox.Uwp/Views/UserControls/CategoryListUserControl.xaml
- Src/MoneyFox.Uwp/Views/UserControls/ModifyAccountUserControl.xaml
- Src/MoneyFox.Uwp/Views/UserControls/ModifyPaymentUserControl.xaml
Removed EntranceNavigationTransitionInfo.IsTargetElement="True" from all user controls and ensured it was added to all root elements in all pages to ensure consistent page transitions. 
The transition animation does not need to be in place on the user controls as it's effect will be applied further up the visual tree, so has been removed from all user controls which will always be displayed inside a page element.
Issue: #1497
- Bugfix
Current behavior is described in issue #1497
All pages show a page entry transition animation consistent with Fluent Design guidelines.
Fix not applicable to Android or iOS platforms. No tests are applicable for this type of change.
> Ensure consistent page transitions for all pages.

- Src/MoneyFox.ServiceLayer/ViewModels/AccountListViewModel.cs
Remove hard-coded account id, replacing it with the accountToDelete.Id so that the actual account can be deleted successfully.
Issue: #1526
- Bugfix
Accounts can't be deleted.
An Account can be deleted.
> Fix Account Deletion - Remove hard-coded account id

- Src/MoneyFox.Uwp/Services/NavigationService.cs
- Src/MoneyFox.Uwp/WindowsShellViewModel.cs
Issue: #
https://github.com/MoneyFox/MoneyFox/issues/1390
Feature
Nothing happens when using mouse back/forward buttons
Mouse back/forward buttons will navigate back and forward in any window/UI element
Windows only feature.
Hard to test without physically pressing mouse buttons
The code:
Windows.UI.Core.CoreWindow.GetForCurrentThread().PointerPressed += On_PointerPressed;
Feels a little out of place.
Let me know if you have any other solution/idea.
The normal KeyboardAccelerators does not work for mouse buttons.
rootFrame.PointerPressed += On_PointerPressed;
Only works when mouse is on UI elements.
> Added support for back and forward navigation via mouse buttons

- Src/MoneyFox.Application/Resources/Strings.Designer.cs
- Src/MoneyFox.Application/Resources/Strings.resx
- Src/MoneyFox.Uwp/MoneyFox.Uwp.csproj
- Src/MoneyFox.Uwp/Package.Appxmanifest
- Src/MoneyFox.Uwp/Views/AppShell.xaml
required new resource strings to be added. Added a new resource for consistency for adding payment title
Issue: #1225
https://github.com/MoneyFox/MoneyFox/issues/1225
- Other... Please describe: UI & Resource change
the main navigation items didn't have tool tips
I added tool tips to the windows application
I did not test on all platforms because this was a Windows platform UI change and adding resource strings (no modification to existing)
- [ x] Tested code on Windows
- [ x] Contains **NO** breaking changes
> adding tooltips for menu items

- Src/MoneyFox.Win.Infrastructure/Adapters/BrowserAdapter.cs
Issue: #2210 
- Bugfix
- Application crashes if the user clicks on any links within the "About" section of the settings, and links do not open in the browser.
- The links now open successfully in the user's browser, and the application does not crash.
- All tests pass.
> Fix for issue #2210 crash when clicking links in "About" section

- Src/MoneyFox.Core.Tests/Aggregates/AccountTests.cs
- Src/MoneyFox.Core/Aggregates/Payments/Payment.cs
- Src/MoneyFox.Core/Aggregates/Payments/RecurringPayment.cs
Issue: #2010 
Bugfix
Changing the Payment Type on a Payment from Transfer to either Expense or Income does not remove the transaction from the Target Account and update the balance accordingly.
Changing the Payment Type on a Payment from Transfer to either Expense or Income now removes the transaction from the Target Account and updates the balance accordingly.
All changes were to the underlying business logic in the MoneyFox.Core project with none in the presentation layer and a new test case was added to validate the behavior.
> Bug fixes and new test case for Issue #2010.

- Src/MoneyFox.Win/MoneyFox.Win/Pages/Payments/PaymentListPage.xaml
Issue: #2262 
- Bugfix
The Modified Date and Creation Date columns are empty in the payment list for accounts.
The Modified Date and Creation Date columns now display the appropriate dates in the payment list for accounts.
Issue was isolated to the Windows form.
> Corrected Modification Date and Creation Date bindings in Payment List on Windows

- Src/MoneyFox.Win/MoneyFox.Win/Converter/BalanceColorConverter.cs
- Src/MoneyFox.Win/MoneyFox.Win/Pages/Accounts/AccountListPage.xaml
- Src/MoneyFox.Win/MoneyFox.Win/Pages/UserControls/BalanceControl.xaml
- Src/MoneyFox.Win/MoneyFox.Win/Style/AppStyles.xaml
- Src/MoneyFox/Common/Styles/DefaultTheme.xaml
- Src/MoneyFox/Converter/BalanceColorConverter.cs
- Src/MoneyFox/Views/Accounts/AccountListPage.xaml
- Src/MoneyFox/Views/Dashboard/DashboardPage.xaml
Issue: #1950 
- Feature
Negative account balance display fields have the same styling as positive/zero account balances.
Negative account balance display fields use an alternate (red) font color to highlight a problem to the end-user.
> Alternate text color for negative account balances.

- Src/MoneyFox.Ui/Views/Accounts/ModifyAccountContentView.xaml
- Src/MoneyFox.Ui/Views/Categories/AddCategoryPage.xaml
- Src/MoneyFox.Ui/Views/Categories/ModifyCategoryContentView.xaml
- Src/MoneyFox.Ui/Views/Payments/AddPaymentPage.xaml
- Src/MoneyFox.Ui/Views/Payments/EditPaymentPage.xaml
- Src/MoneyFox.Ui/Views/Payments/ModifyPaymentContentView.xaml
Issue: -
Fixes that the add and edit payment view does not extend when for example Recurring is activated.
> Add payment view does not extend on ios

- Src/MoneyFox.Ui.Tests/Views/Settings/SettingsViewModelTests.cs
- Src/MoneyFox.Ui/Views/Settings/SettingsViewModel.cs
Issue: fix #2870
- Bugfix
View is always initialized with the currency from the current region.
The region is used as fallback if the default currency wasn't set yet.
> 2870 default currency reverts to chf when setting is opened

- Src/MoneyFox.Ui.Tests/Views/SetupAssistant/SetupAccountViewModelTests.cs
- Src/MoneyFox.Ui/Views/Setup/SetupAccountPage.xaml
- Src/MoneyFox.Ui/Views/Setup/SetupAccountPage.xaml.cs
- Src/MoneyFox.Ui/Views/Setup/SetupAccountsViewModel.cs
Issue: #
https://github.com/MoneyFox/MoneyFox/issues/3021
Feature
User could finish setup wizard without creating an account.
User now needs at least one account to finish setup wizard
Code was not tested on iOS because I do not own any iOS device.
> Make it mandatory that you have at least one account after setup wizard

- Src/MoneyFox.Core/Common/Settings/SettingConstants.cs
- Src/MoneyFox.Core/Common/Settings/SettingsFacade.cs
- Src/MoneyFox.Ui/Controls/CustomStepperWithEntry.xaml
- Src/MoneyFox.Ui/Controls/CustomStepperWithEntry.xaml.cs
- Src/MoneyFox.Ui/Views/Statistics/CategorySpreading/StatisticCategorySpreadingPage.xaml
- Src/MoneyFox.Ui/Views/Statistics/CategorySpreading/StatisticCategorySpreadingPage.xaml.cs
- Src/MoneyFox.Ui/Views/Statistics/CategorySpreading/StatisticCategorySpreadingViewModel.cs
Issue: #2741
https://github.com/MoneyFox/MoneyFox/issues/2741
- Feature
Currently the number of categories included in the category spreading is fix. It would be nice if this could be dynamically selected.
This should be persisted to the settings.
Number of categories included in the category spreading can be changed dynamically via entry or increase/decrease buttons.
It is also persisted to the settings.
Not tested on iOS (Unfortunately, I do not own any Apple product)
Entry is cleared for edge cases as well as any non numeric input.
Number of categories is persisted via SettingsFacade.cs just like in AccountGroup.cs, but I am not so sure with my solution so maybe it needs a correction.
Also text in the new label for the entry is hardcoded in …
> Solution to the issue #2741
